 	<?php 
	if($locales_selected=='ar_AE'){
		$language_class="ar";
	}else{
		$language_class="en";
	}	 
?>
 <div class="left-profile-details  <?php echo $language_class; ?>" id="profile_div" ng-modules="myapp" ng-cloak >
	
	<div  ng-controller="profileController" ng-switch on="profileData.switch">
		<div class="change-group_banner group_settings_dropdown" >
			<a href="javascript:void(0);"  data-toggle="dropdown" >
				<img src="<?php echo $this->basePath(); ?>/public/images/arrow_options_red.svg" />
			</a>
			<ul class="dropdown-menu color-trans arrow_box arrow_right" role="menu" aria-labelledby="update_banner">
				 <li  ng-if="myprofile == 1">
					<a href="javascript:void(0);" ng-if="myprofile == 1" class="" id="edit_profile-butn"  ng-click="switchForm()"><?php echo $this->translate('Edit Profile','default'); ?></a>
				</li>
				<li ng-if="myprofile != 1 && friendship_status == 'friends'"  >
					<a href="javascript:void(0);"  ng-click="unFriendRequest()"><?php echo $this->translate('Unfriend','default'); ?></a>
				</li>
				<li ng-if="myprofile != 1 && friendship_status == 'requested'" >
					<a  href="javascript:void(0);" ><?php echo $this->translate('Pending','default'); ?></a>	
				</li>
				 <li  ng-if="myprofile != 1">
					<span class="group_join"> <a class="user_comment_report" href="javascript:void(0);"   ng-click="ReportUser('User',profileuser_id)" data-toggle="modal" data-target="#report_user"  ><?php echo $this->translate('Report this user','default'); ?></a></span>
				</li>
				
			</ul>
		</div>
    	<div class="left-profile-inner" id="profile_details" ng-switch-when="1" >
        	<div class="profile-img-left">
				<a href="javascript:void(0);"  data-toggle="modal" data-target="#view_profile-image" ng-click="loadPopup()">
				<img alt="" ng-if="profile_pic!=null&&profile_pic!=''" src="<?php echo $this->basePath(); ?>/public/datagd/profile/{{profileuser_id}}/{{ profile_pic }}">
				<img alt="" ng-if="(profile_pic==null||profile_pic=='')&&(user_fbid!=null&&user_fbid!='')" src="https://graph.facebook.com/{{user_fbid}}/picture?width=66&&height=66">
				<img alt="" ng-if="(profile_pic==null||profile_pic=='')&&(user_fbid==null||user_fbid=='')" src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg">
                 </a>                    
			</div>
            <div class="profile-name-left">
            	{{username}}
                <span><i class="group-location"></i>{{city}}, {{country_code_locale}}</span>
            </div>
            <div class="profile-brief-left">
            	{{about}}
            </div>
            <div class="profile-edit-left"   >
				
				<div ng-show="request_ajax_loader" class="loading"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> </div>
				<div ng-show="!request_ajax_loader">
            	
				<a href="javascript:void(0);" ng-if="myprofile != 1 && friendship_status == 'add friend'" class="default_butn_blue" ng-click="sentFriendRequest()"><?php echo $this->translate('Add Friend','default'); ?></a>
				<a href="javascript:void(0);" ng-if="myprofile != 1 && friendship_status == 'pending'" class="friend_accept" ng-click="acceptFriendRequest()" title="Accept request"></a>
				<a href="javascript:void(0);" ng-if="myprofile != 1 && friendship_status == 'pending'" class="friend_ignore" ng-click="rejectFriendRequest()" title="Ignore Request"></a>
				
				
				</div>
            </div>
            
        </div>
        
        <div class="left-profile-inner" id="profile_details-edit" ng-switch-when="2"  >
        	<div class="profile-img-left profile_img-edit">
            	<img alt="" ng-if="profile_pic!=null&&profile_pic!=''" src="<?php echo $this->basePath(); ?>/public/datagd/profile/{{profileuser_id}}/{{ profile_pic }}">
				<img alt="" ng-if="(profile_pic==null||profile_pic=='')&&(user_fbid!=null&&user_fbid!='')" src="https://graph.facebook.com/{{user_fbid}}/picture?width=500&&height=500">
				<img alt="" ng-if="(profile_pic==null||profile_pic=='')&&(user_fbid==null||user_fbid=='')" src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg">
            	<a href="javascript:void(0);"   data-toggle="modal" data-target="#upload_profile-image" id="profile_image_edit">
                    <span>
                        <i class="change_cover"></i><br>
                       <?php echo $this->translate('Change','default'); ?> 
                    </span>
                </a>
            </div>
            <div class="login-field profile_edit-field">
            	<input type="text" placeholder="<?php echo $this->translate('Username and Lastname','default'); ?>"   name="name" ng-model="user.username" required>
            </div>
			<div class="fixed-search profile-edit_search">
				<a id="dLabel_gender" href="javascript:void(0)" data-toggle="dropdown"  >{{user_gender}}</a>
				<ul class="color-trans dropdown-menu border_radius "  aria-labelledby="dLabel_gender" role="menu">
					 
					<li ng-click="showGenderDropdown('male')" ><a href="javascript:void(0);"><?php echo $this->translate('Male','default'); ?></a></li>
					<li ng-click="showGenderDropdown('female')"><a href="javascript:void(0);"><?php echo $this->translate('Female','default'); ?></a></li>					
				</ul>
				
                 
            </div>
			<div class="login-field profile_edit-field">
            	<input type="text" placeholder="<?php echo $this->translate('Date of Birth','default'); ?>"  id="dateofbirth" name="dob" ng-model="user.dateofbirth" >
            </div>
			<div ng-show="loading" class="loading"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> </div>
            <div class="fixed-search profile-edit_search">
				
				<a id="dLabel_country" href="javascript:void(0)" data-toggle="dropdown"  >{{country_title}}</a>
				<ul class="color-trans dropdown-menu border_radius " aria-labelledby="dLabel_country" role="menu">
					<li  ng-repeat="item in countrylist" ng-click="showCountryDropdown(item.country_id,item.country_title,item.country_title_locale)"  ><a href="javascript:void(0);">{{item.country_title_locale}}</a></li>					 			
				</ul>
			
                 
            </div>
			<div class="fixed-search profile-edit_search cityDropdown" >
				<a id="dLabel_city" href="javascript:void(0)" data-toggle="dropdown"  >{{city}}</a>
				<ul class="color-trans dropdown-menu border_radius" aria-labelledby="dLabel_city" role="menu">					
					<li  ng-repeat="item in citylist" ng-click="showCityDropdown(item.city_id,item.name,item.city_locale)" ><a href="javascript:void(0);">{{item.city_locale}}</a></li>					 			
				</ul>
                 
            </div>
            <div class="profile_edit-textarea" ng-model="about">
            	<textarea name="" ng-model="user.about" placeholder="<?php echo $this->translate('Biography','default'); ?>">{{about}} </textarea>
            </div>
            
            <div class="profile-edit-left">
            	<a href="javascript:void(0);" class="default_butn_normal" ng-click="cancelForm()" ><?php echo $this->translate('Cancel','default'); ?></a> <a href="javascript:void(0);" class="default_butn_blue" ng-click="saveForm(user)"><?php echo $this->translate('Save Changes','default'); ?></a>
				
            </div>
            
        </div>
	<div class="pop_bg modal fade" id="upload_profile-image" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog upload-img_popup">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <div class="clear"></div>
          </div>
          <div class="modal-body signup_body">
                <div class="step1_outer">
                    <h3><?php echo $this->translate('Position and Size Your Photo','default'); ?></h3>
                    <div class="profile-pic_preview_outer">
                    	<div class="image-editor" id="profile_pic_editor_profile">
                              <div class="browse-profile_image"><input type="file" class="cropit-image-input" id="profile_image_file_edit"></div>
                              <!-- .cropit-image-preview-container is needed for background image to work -->
                              <div class="cropit-image-preview-container">
                                <div class="cropit-image-preview"></div>
                              </div>
                              <div class="image_zoom-bar">
                              	<input type="range" class="cropit-image-zoom-input">
                              </div>
							  <div id="edit_profilepic_process">
							  </div>
                              <div class="upload-img_butns">
                              	<a href="javascript:void(0);" class="default_butn_red" ng-click="closeCropWindow()"><?php echo $this->translate('Cancel','default'); ?></a>
								<div ng-if="aboutmeAjax==1" class="loading"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> </div>
                                <a href="javascript:void(0);"  ng-if="aboutmeAjax==0" class="default_butn_blue" ng-click="cropImage()"><?php echo $this->translate('Apply','default'); ?></a>
                              </div>
                              
                        </div>
                    </div>
                    
                </div>
            
          </div>
          
        </div>
      </div>
    </div>
	<div class="pop_bg modal fade" id="view_profile-image" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog view-img_popup">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo $this->translate('Close','default'); ?></span></button>
            <div class="clear"></div>
          </div>
          <div class="modal-body signup_body">
                <img alt="" ng-if="profile_pic!=null&&profile_pic!=''" src="<?php echo $this->basePath(); ?>/public/datagd/profile/{{profileuser_id}}/{{ profile_pic }}">
				<img alt="" ng-if="(profile_pic==null||profile_pic=='')&&(user_fbid!=null&&user_fbid!='')" src="https://graph.facebook.com/{{user_fbid}}/picture?width=500&&height=500">
				<img alt="" ng-if="(profile_pic==null||profile_pic=='')&&(user_fbid==null||user_fbid=='')" src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg">            
          </div>
          
        </div>
      </div>
    </div>
		<div class="pop_bg modal fade" id="report_user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog login_popup">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo $this->translate('Close','default'); ?></span></button>
            <div class="clear"></div>
          </div>
          <div class="modal-body signup_body">
			<div id="signup_step1" ng-if="user_ajax_loader_reportpost==1">
				<img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> 
			</div>
			<div id="signup_step1" ng-if="user_ajax_loader_reportpost==0">
				<div class="error-common" id="profile_report_error"></div>
				<div class="success-common" id="profile_report_success"></div>
				<div class="step1_outer">
					<div class="select_group-type" ng-repeat="items in user_reasons">			 
                    	<input type="radio" name="spam_type" id="{{items.reason_id}}" value="{{items.reason_id}}" ng-click="user_selectReason(items.reason_id,items.reason)" ng-model="user_spam.reason_id">
                        <label for="{{items.reason_id}}"><i class="radio-styled"></i> <i class="group-public_black"></i>{{items.reason_locale}}</label>                       
                        <div class="clear"></div>
                    </div>
					<div class="login-field" ng-if="user_enableReportReason==1">
					<textarea placeholder="<?php echo $this->translate('Please type your reason','default'); ?>" ng-model="user_spam.otherReason"></textarea>
					</div>
					<div class="clear"></div>
					<div class="signup_button" ng-if="profilereportAjaxLoader==0">                        
                         <a ng-click="user_sendReport(user_spam)" id="go_step-2" class="default_butn_blue" href="javascript:void(0);"><?php echo $this->translate('Submit','default'); ?></a></div>
                        <div class="clear"></div>
                    </div>
					<div class="signup_button" ng-if="profilereportAjaxLoader==1">                        
                       <img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> 
					</div>
					<div class="clear"></div>
				</div> 
			</div>
          </div>
          
        </div>
      </div>
     </div>   
        <div class="left-interest-fixed" id="intrestarea" ng-controller="intrestController">
        	<div class="interest_head-left">
            	<?php echo $this->translate('Interested In','default'); ?>:
                <a href="javascript:void(0);" ng-if="myprofile == 1" data-toggle="modal" data-target="#interest_popup" ng-click="loadPopup()"><?php echo $this->translate('Add / Remove Interests','default'); ?></a>
                <div class="clear"></div>
            </div>
            <div class="profile-category_icons">
				<a href="javascript:void(0);" ng-repeat="items in intrest"   ng-if="items.tag_category_icon!=''" ng-mouseover="categoryHover(items.tag_category_id)" ng-mouseleave="categoryReset()">
					<img src="{{categoryImagePath}}{{items.tag_category_icon}}" alt="{{items.tag_category_title_locale}}" />
				</a>
				<a href="javascript:void(0);" ng-repeat="items in intrest" ng-if="items.tag_category_icon==''" ng-mouseover="categoryHover(items.tag_category_id)" ng-mouseleave="categoryReset()">
					<img src="<?php echo $this->basePath(); ?>/public/images/category-icon.svg" alt="{{items.tag_category_title_locale}}" />
				</a>
            </div>
            <div class="profile-interest_list"> 
			<span ng-repeat="tags in userIntrests" ng-if="myprofile!= 1&&checkCommonIntrests(tags.tag_id)&&(HoverCategory==tags.category_id)" style="text-transform:capitalize;" class="interest_common"> {{tags.tag_title}}<i>.</i></span>
			<span ng-repeat="tags in userIntrests" ng-if="(myprofile== 1||!checkCommonIntrests(tags.tag_id))&&(HoverCategory==tags.category_id)" style="text-transform:capitalize;">{{tags.tag_title}}<i>.</i></span>
               
            </div>
            <div class="pop_bg modal fade" id="interest_popup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			  <div class="modal-dialog interest_popup">
				<div class="modal-content">
				  <div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<div class="clear"></div>
				  </div>
				  <div class="modal-body signup_body <?php echo $language_class; ?>">
					<div class="step1_outer">
						<h3><?php echo $this->translate('Add More Interests','default'); ?></h3>
						<div class="interest_category-outer dropdown_icons-outer" ng-switch on="intrest.switch">
							<a id="dLabel_intrest" data-toggle="dropdown" class="" href="javascript:void(0);">
								<img ng-if="selectedIntrestCategoryIcon!=''" src="{{categoryImagePath}}{{selectedIntrestCategoryIcon}}" alt="{{selectedIntrestCategory}}" />
								<img ng-if="selectedIntrestCategoryIcon==''" src="<?php echo $this->basePath(); ?>/public/images/category-icon.svg" alt="{{selectedIntrestCategory}}" /> 
							{{selectedIntrestCategory}}
							</a>
							<ul class="color-trans dropdown_icons border_radius dropdown-menu" aria-labelledby="dLabel_intrest" role="menu"   ng-switch-when="1">
								<div ng-init="enableIntrestScrollBar()" id="intrest_category_list">
								 
								<li   ng-repeat="item in tagCategory">
								<a href="javascript:void(0);" ng-click="selectCategory(item.tag_category_id,item.tag_category_icon,item.tag_category_title,item.tag_category_title_locale)">
								<img ng-if="item.tag_category_icon!=''" src="{{categoryImagePath}}{{item.tag_category_icon}}" alt="{{item.tag_category_title_locale}}" />
								<img ng-if="item.tag_category_icon==''" src="<?php echo $this->basePath(); ?>/public/images/category-icon.svg" alt="{{item.tag_category_title_locale}}" /> 
								{{item.tag_category_title_locale}}</a>
								</li>
								</div>								
							</ul>	
							<div ng-switch-when="2" class="loading"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> </div>
						</div>
						<div class="interest_search-outer" >
							<div class="fixed-search interest_search">
								<input type="text" placeholder="<?php echo $this->translate('Search Interest','default'); ?>" name="search" ng-model="tag_search" >
								<a href="javascript:void(0);"></a>
							</div>
						</div>
						<div class="clear"></div>
						<div class="popup_interest-lists" ng-show="showtags"  >
							<a class="interest_add" remove-on-click href="javascript:void(0);" ng-repeat="items in filtered = (tags | filter:tag_search) | limitTo:tag_limit" ng-click="addToSelected(items.category_id,items.tag_id,items.tag_title_locale);remove()">{{items.tag_title_locale}}<span></span></a>	
							<a class="tag_show_more" ng-show="showmoretags" ng-click="tag_limit = tag_limit + tag_inc_limit" ng-init="tag_limit = tag_inc_limit" ng-hide="filtered.length <= tag_limit">
                             <?php echo $this->translate('More','default'); ?> ...
                            </a> 						
						</div>
						<h3><?php echo $this->translate('Your Interests','default'); ?></h3>
						<div class="selected_interest">
						<img  ng-repeat="items in objSelectedCategory"   ng-if="items.category_icon!=''" src="{{categoryImagePath}}{{items.category_icon}}" alt="{{items.category_title}}" />
						<img ng-repeat="items in objSelectedCategory" ng-if="items.category_icon==''" src="<?php echo $this->basePath(); ?>/public/images/category-icon.svg" alt="{{items.category_title}}" /> </div>
						<div class="popup_interest-lists">
							<a class="interest_added" href="javascript:void(0);" ng-repeat="items in objSelectedTags" remove-on-click ng-click="remove();removeFromSelected(items.tag_name,items.category)" >{{items.tag_name}}<span></span></a>
							 
						</div>
						
						<div class="login_button">
							<a href="javascript:void(0);" class="default_butn_blue" ng-click="AddToIntrest()"><?php echo $this->translate('Done','default'); ?></a>
						</div>
					</div>
				 </div>
				  
				</div>
			  </div>
			</div>
        </div>
	
    </div>
<div id="profile_dialog" title="" class="common_error" style="display:none"></div>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/public/js/jquery.cropit.js"></script>
<script type="text/javascript" src='<?php echo $this->basePath(); ?>/public/js/jquery-customSelect.js'></script>
<script>
	$(document).on("click","#edit_profile-butn",function(){	
		$( "#dateofbirth" ).datepicker({ changeYear: true , dateFormat: "yy-mm-dd", maxDate: new Date(<?php echo date("Y");?>, <?php echo date("m");?> - 1, <?php echo date("d");?> ),  yearRange: "1900:<?php echo date("Y");?>" });
	});
	//LoadCustomeBox();
	function LoadCustomeBox(){ 
		 $('select.styled').customSelect();
	}
	var profile = <?php echo json_encode($profile_data); ?>; 
	var image_paths = <?php echo json_encode($image_folders); ?>;
	var app = angular.module('myapp',[]);
	app.config(function ($httpProvider) {
		$httpProvider.defaults.transformRequest = function(data){
			if (data === undefined) {
				return data;
			}
			return $.param(data);
		}
	});
	app.controller('profileController',function($scope, $http){	 
		$scope.user = {};
		$scope.username=profile.user_given_name;
		$scope.loading=false;
		$scope.user.username=profile.user_given_name;
		$scope.user.country=profile.country_id;
		$scope.user.city=profile.city_id;
		$scope.user.gender = profile.user_gender;
		$scope.user.dateofbirth = profile.user_profile_dob;
		$scope.city=profile.city_name;
		$scope.country_title = profile.country_title;
		$scope.country=profile.country_code;
		$scope.country_code_locale=profile.country_code_locale;
		$scope.about=profile.user_profile_about_me;
		$scope.user.about=profile.user_profile_about_me;
		$scope.myprofile= <?php echo $myprofile; ?>;
		$scope.friendship_status = '<?php echo $friendship_status; ?>';
		$scope.profileData = {};
		$scope.profileData.switch  =  1;
		$scope.request_ajax_loader  = 0;
		$scope.profile_pic =profile.profile_photo;
		$scope.user_fbid = profile.user_fbid;
		$scope.profileuser_id=profile.user_id;
		$scope.genderdrpClass = "dropdown_close";
		$scope.countrydrpClass =  "dropdown_close";
		$scope.citydrpClass = "dropdown_close";
		$scope.isGenderDropVisible = 0;
		$scope.isCountryDropVisible = 0;
		$scope.isCityDropVisible = 0;
		$scope.isCityDefault = 0;
		if(profile.user_gender == '' ||profile.user_gender == null){
			$scope.user_gender = '<?php echo $this->translate('Gender','default'); ?>';
		}else{
			if(profile.user_gender =='male'){
				$scope.user_gender = '<?php echo $this->translate('Male','default'); ?>';
			}
			if(profile.user_gender =='female'){
				$scope.user_gender = '<?php echo $this->translate('Female','default'); ?>';
			}
		}		
		$scope.switchForm = function() {
			$scope.loading=true;
			$scope.profileData.switch  =  2;
			url  = baseurl+'/country/ajaxCountryList';
			$http({
				method: 'POST',
				url: url
			}).success(function(data, status, headers, config) {
				$scope.countrylist=data.countries;
				var index = 0;
				angular.forEach(data.countries, function(dataset){
					if(dataset.country_code == $scope.country){ index++;
						$scope.CitySelect(dataset.country_id);
						$scope.loading=false;
					} 
				});
				if(index==0){$scope.loading=false;}
			}).error(function(data, status, headers, config) {				
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			});
		};
		$scope.CitySelect = function(country_value){
			$scope.loading=true;
			url  = baseurl+'/city/ajaxCitiesList';
			$http.post(url,{country_id:country_value}, {headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}			
			).success(function(data, status, headers, config) {
				$scope.citylist=data.cities;	$scope.loading=false;
				var select_city = 0;
				angular.forEach(data.cities, function(dataset){
					if(profile.city_id==dataset.city_id){
						$scope.city = dataset.city_locale;
						$scope.user.city =dataset.city_id;
						select_city = 1;
					}
				});
				if(select_city==0){
					$scope.city = data.cities[0].city_locale;
					$scope.user.city =data.cities[0].city_id;
				}					
			}).error(function(data, status, headers, config) {				
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			}); 
		};
		$scope.cancelForm = function() {
			if(profile.user_gender == '' ||profile.user_gender == null){
				$scope.user_gender = '<?php echo $this->translate('Gender','default'); ?>';
			}else{
				if(profile.user_gender =='male'){
					$scope.user_gender = '<?php echo $this->translate('Male','default'); ?>';
				}
				if(profile.user_gender =='female'){
					$scope.user_gender = '<?php echo $this->translate('Female','default'); ?>';
				}
			}
			$scope.profileData.switch  =  1;
			$scope.user.city=profile.city_id;
			$scope.city=profile.city_name;
		};
		$scope.saveForm = function(user) {  
			url  = baseurl+'/user/updateProfile/<?php echo $profilename; ?>';
			$http.post(url,{user_name:user.username,country:user.country,city:user.city,about:user.about,gender:user.gender,dateofbirth:user.dateofbirth}, {headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) {
				if(data.return_array.process_status == 'success'){
					$scope.username=user.username;	
					angular.forEach($scope.citylist,function(dataset){if(dataset.city_id == user.city){$scope.city =dataset.name }});					 
					angular.forEach($scope.countrylist,function(dataset){if(dataset.country_id == user.country){$scope.country =dataset.country_code }});						 
					$scope.about=user.about;
					$scope.profileData.switch  =  1;
					window.location.reload();
				}else{					
					$("#profile_dialog").html(data.return_array.process_info);
					$( "#profile_dialog" ).dialog(); 
				}				     
			}).error(function(data, status, headers, config) {				
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			});
		};
		$scope.sentFriendRequest  = function(){
			$scope.request_ajax_loader  = 1;
			url  = baseurl+'/user/sentFriendRequest/<?php echo $profilename; ?>';
			$http({
				method: 'POST',
				url: url
			}).success(function(data, status, headers, config) {
				if(data.return_array.process_info==''){
					$scope.friendship_status ='requested';
					$scope.request_ajax_loader  = 0;
				}else{					
					$("#profile_dialog").html(data.return_array.process_info);
					$( "#profile_dialog" ).dialog(); 
				}
			}).error(function(data, status, headers, config) {				
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			});
		}
		$scope.acceptFriendRequest  = function(){
			$scope.request_ajax_loader  = 1;
			url  = baseurl+'/user/acceptFriendRequest/<?php echo $profilename; ?>';
			$http({
				method: 'POST',
				url: url
			}).success(function(data, status, headers, config) {
				if(data.return_array.process_info==''){
					$scope.friendship_status ='friends';
					$scope.request_ajax_loader  = 0;
				}else{					
					$("#profile_dialog").html(data.return_array.process_info);
					$( "#profile_dialog" ).dialog(); 
				}
			}).error(function(data, status, headers, config) {				
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			});
		}
		$scope.rejectFriendRequest  = function(){
			$scope.request_ajax_loader  = 1;
			url  = baseurl+'/user/rejectFriendRequest/<?php echo $profilename; ?>';
			$http({
				method: 'POST',
				url: url
			}).success(function(data, status, headers, config) {
				if(data.return_array.process_info==''){
					$scope.friendship_status ='add friend';
					$scope.request_ajax_loader  = 0;
				}else{					
					$("#profile_dialog").html(data.return_array.process_info);
					$( "#profile_dialog" ).dialog(); 
				}
			}).error(function(data, status, headers, config) {				 
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			});
		}
		$scope.unFriendRequest  = function(){
			$scope.request_ajax_loader  = 1;
			url  = baseurl+'/user/unFriendRequest/<?php echo $profilename; ?>';
			$http({
				method: 'POST',
				url: url
			}).success(function(data, status, headers, config) {
				if(data.return_array.process_info==''){
					$scope.friendship_status ='add friend';
					$scope.request_ajax_loader  = 0;
				}else{					
					$("#profile_dialog").html(data.return_array.process_info);
					$( "#profile_dialog" ).dialog(); 
				}
			}).error(function(data, status, headers, config) {				
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			});
		}
		$scope.aboutmeAjax =0;
		$scope.cropImage = function(){			
			var imageData = $('.image-editor').cropit('export');				 
			$scope.aboutmeAjax =1;	
			url = baseurl + '/user/updatProfilePic';
			$http.post(url,{imageData:imageData},{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}
			).success(function(data, status, headers, config) {
				 if(data.return_array.process_status == 'success'){					  
					$scope.aboutmeAjax =0;		
					window.location.reload();
				 }else{
					$("#profile_dialog").html(data.return_array.process_info);
					$( "#profile_dialog" ).dialog();
					$scope.aboutmeAjax =0;		
				 }
			}).error(function(data, status, headers, config) {
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			}); 				 
		}
		$scope.closeCropWindow = function(){
			$('#upload_profile-image').modal("hide");
		}		
		$scope.showGenderDropdown = function(id){			 
			$scope.user.gender = id;
			if(id =='male'){
				$scope.user_gender = '<?php echo $this->translate('Male','default'); ?>';
			}
			if(id =='female'){
				$scope.user_gender = '<?php echo $this->translate('Female','default'); ?>';
			}			 
		}
		$scope.showCountryDropdown = function(id,title,title_locale){				 
			$scope.user.country = id,
			$scope.country_title = title_locale,					 
			$scope.CitySelect($scope.user.country);				
		}
		$scope.showCityDropdown = function(id,title,title_locale){
			$scope.user.city = id;
			$scope.city = title_locale;				
		}
		$scope.user_reasons= [];
		$scope.user_ajax_loader_reportpost = 1;
		$scope.user_reportSelectedContentId = '';
		$scope.user_reportSelectedContentType = '';
		$scope.user_selectedReasonId='';
		$scope.user_selectedReasonType='';
		$scope.user_enableReportReason=0;;
		$scope.profilereportAjaxLoader =0;
		$scope.user_spam={};
		$scope.ReportUser = function(type,content_id){
			$("#profile_report_error").html('');
			$("#profile_report_success").html('');
			$scope.user_ajax_loader_reportpost = 1;
			$scope.user_reasons= [];
			$scope.user_reportSelectedContentId = content_id;
			$scope.user_reportSelectedContentType = type;
			url  = baseurl+'/spam/getreasons';
			$http.post(url,
			{	
				type:type,content_id:content_id
			},
			{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) {
				if(data.return_array.process_status == 'success'){
					$scope.user_reasons=data.return_array.reasons;
					$scope.user_ajax_loader_reportpost = 0;
				}else{					
					$("#profile_dialog").html(data.return_array.process_info);
					$( "#profile_dialog" ).dialog(); 	
					$("#report_user").modal("hide");
				}				     
			}).error(function(data, status, headers, config) {
				// alert("Error occured. Please try again");
			});	
		}
		$scope.user_selectReason = function(reason_id,reasontype){
			$scope.user_selectedReasonId=reason_id;
			$scope.user_selectedReasonType=reasontype;
			if(reasontype == 'Other'){
				$scope.user_enableReportReason=1;
			}else{
				$scope.user_enableReportReason=0;
			}
		}
		$scope.user_sendReport = function(frmspam){
			$("#profile_report_success").html();
			$("#profile_report_success").fadeOut('slow');	
			if($scope.user_selectedReasonType == ''){
				$("#profile_report_error").html("<?php echo $this->translate('Select one reason','default'); ?>");
				$("#profile_report_error").fadeIn("slow");
			}else if($scope.user_selectedReasonType == 'Other'&&frmspam.otherReason=='' ){
				$("#profile_report_error").html("<?php echo $this->translate('Please enter a reason','default'); ?>");
				$("#profile_report_error").fadeIn("slow");
			}else{
				$("#profile_report_error").html('');
				$("#profile_report_error").fadeOut('slow');
				$scope.profilereportAjaxLoader =1;
				url  = baseurl+'/spam/sentreport';
				$http.post(url,
				{	
					type:$scope.user_reportSelectedContentType,content_id:$scope.user_reportSelectedContentId,reason_id:frmspam.reason_id,otherReason:frmspam.otherReason
				},
				{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
				).success(function(data, status, headers, config) {
					$scope.profilereportAjaxLoader =0;
					if(data.return_array.process_status == 'success'){
						$("#profile_report_success").html("<?php echo $this->translate('The  report is successfully submitted','default'); ?>");
						$("#profile_report_success").fadeIn('slow');						 
						$scope.spam={};
						//$("#report_user").modal("hide");
					}else{						 
						$("#profile_report_error").html(data.return_array.process_info);
						$("#profile_report_error").fadeIn("slow");
						//$("#report_user").modal("hide");
					}				     
				}).error(function(data, status, headers, config) {
					$scope.profilereportAjaxLoader =0;
					 //alert("Error occured. Please try again");
				});	
			}
		}		
	});		 
	app.controller('intrestController',function($scope, $http){
		$scope.tag_search='';
		$scope.intrest= <?php echo json_encode($user_tags); ?>;
		$scope.categoryImagePath=(image_paths.tag_category!='')?baseurl+"/public/"+image_paths.tag_category:baseurl+'/public/images/';
		$scope.objSelectedCategory =  new Array();
		$scope.objSelectedTags = new Array();
		$scope.intrest.switch = 2; 
		$scope.myprofile= <?php echo $myprofile; ?>;
		$scope.myIntrest = <?php echo json_encode($myIntrests); ?>;
		$scope.userIntrests = <?php echo json_encode($userIntrests); ?>;
		$scope.tag_limit = 25;
		$scope.tag_inc_limit = 25;
		$scope.selectedIntrestCategory = '';
		$scope.selectedIntrestCategoryIcon = '';
		$scope.HoverCategory = 0;
		$scope.checkCommonIntrests = function(tag_id){
			var is_exist = -1;
			for(i=0;i<$scope.myIntrest.length;i++){
				if($scope.myIntrest[i].tag_id == tag_id){	
					is_exist =i;
				}
			}
			if(is_exist!=-1){return true;}else{return false;}
		}
		$scope.loadPopup = function(){	
			$scope.tag_limit = 25;
			$scope.intrest.switch = 2;
			url = baseurl+'/tag/getAllActiveCategories';
			$http({
				method: 'POST',
				url: url
			}).success(function(data, status, headers, config) {
				$scope.tagCategory=data.tag_category;
				$scope.selectedIntrestCategory = data.tag_category[0].tag_category_title_locale;
				$scope.selectedIntrestCategoryIcon = data.tag_category[0].tag_category_icon;
				//$scope.selectedCategory = data.tag_category[0].tag_category_id;
				$scope.getTags(data.tag_category[0].tag_category_id);
				//$scope.selectedCategory ='All';
				// $scope.getTags('All');
				$scope.intrest.switch = 1;
				$scope.selectedIndex = 0;
			}).error(function(data, status, headers, config) {					
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			});
			url = baseurl+'/user/myintrests/<?php echo $profilename; ?>';
			$http({
				method: 'POST',
				url: url
			}).success(function(data, status, headers, config) {
				if(data.return_array.process_info==''){
					$scope.objSelectedCategory =  new Array();
					$scope.objSelectedTags = new Array();
					angular.forEach(data.return_array.tag_category, function(dataset){ 
						$scope.objSelectedCategory.push({
							category:dataset.tag_category_id,category_title:dataset.tag_category_title,category_icon:dataset.tag_category_icon
						});										 
					});
					angular.forEach(data.return_array.tags, function(dataset){ 
						$scope.objSelectedTags.push({
							category:dataset.category_id,tag_id:dataset.tag_id,tag_name:dataset.tag_title
						});										 
					});
				}else{					    
					$("#profile_dialog").html(data.return_array.process_info);
					$( "#profile_dialog" ).dialog(); 
				}
			}).error(function(data, status, headers, config) {					
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			});
		};
		$scope.isVisible = 0;
		$scope.drpClass = "dropdown_close";
		$scope.selectedIndex = 0;	
		$scope.tags = {};
		$scope.showtags = 0;			
		$scope.selectedCategory = '';
		$scope.showmoretags = 0;			
		$scope.enableIntrestScrollBar = function(){
			 $('#intrest_category_list').slimScroll({
			  color: '#00f',height:'250px'
			});				 
		}
		$scope.selectCategory = function(category,icon,title,title_locale){  
			$scope.selectedIntrestCategory = title_locale;
			$scope.selectedIntrestCategoryIcon = icon; 
			$scope.selectedCategory = category;
			$scope.tag_limit = 25;
			$scope.showmoretags = 0;
			$scope.showtags = 0;	
			$scope.getTags(category);	
		};
		$scope.getTags = function(category){
			$scope.showtags = 0;
			$scope.showmoretags = 0;
			url  = baseurl+'/tag/getAllTagsOfSelectedCategory';				
			$http.post(url,{category_id:category,search:$scope.tag_search}, {headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) { 
				if(data.tags.length>0){
				$scope.tags = data.tags; 	
				$scope.showtags = 1;
				}else{$scope.showtags = 0;}
				if(data.tags.length > $scope.tag_limit) {
				$scope.showmoretags=1; } else { $scope.showmoretags =0; }
			}).error(function(data, status, headers, config) {
				
				$("#profile_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();	
			});
		};
		$scope.searchTag = function(){
			$scope.getTags($scope.selectedCategory);
		}			
		$scope.objSelectedTags = new Array();
		$scope.addToSelected = function(category,tag_id,tag_name){ 
			var incexist = 0;
			angular.forEach($scope.objSelectedTags, function(dataset){ 
				if(dataset.tag_name == tag_name){incexist++;}
			});				
			if(incexist == 0){
				$scope.objSelectedTags.push({
					category:category,tag_id:tag_id,tag_name:tag_name
				});
			}
			angular.forEach($scope.tagCategory, function(dataset){ 
				if(dataset.tag_category_id == category){
					var incexist = 0;
					angular.forEach($scope.objSelectedCategory, function(datasets){ 
						if(datasets.category_icon == dataset.tag_category_icon){incexist++;}
						 
					});	
					if(incexist ==0){
						$scope.objSelectedCategory.push({
							category:dataset.tag_category_id,category_title:dataset.tag_category_title,category_icon:dataset.tag_category_icon
						});	
					}
				}
			   });
			 
		};
		$scope.removeFromSelected = function(tag_name,category){ 			 
			var array_index = $scope.getArrayIndex($scope.objSelectedTags,'tag_name',tag_name);
			$scope.objSelectedTags.splice( array_index, 1 );
			var incexist = 0;
			angular.forEach($scope.objSelectedTags, function(dataset){ 
				if(dataset.category == category){incexist++;}
			});				
			if(incexist == 0){
				var array_index = $scope.getArrayIndex($scope.objSelectedCategory,'category',category);
				$scope.objSelectedCategory.splice( array_index, 1 );
			}
		};
		$scope.getArrayIndex = function(arr_elemnt,key,item){ 
			var incexist = -1;
			for(i=0;i<arr_elemnt.length;i++) {
				if(arr_elemnt[i][key] == item){incexist = i;}
			}
			return incexist;
		};
		$scope.AddToIntrest = function(){
			var newtags = new Array();
			var incexist = 0;
			angular.forEach($scope.objSelectedTags, function(dataset){ 
				newtags[incexist] = dataset.tag_id;
				incexist++;
			});
			url  = baseurl+'/user/updateTags/<?php echo $profilename; ?>';
			$http.post(url,{tags:newtags}, {headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) { 
				$scope.intrest=data.return_array.user_tags;
				$scope.userIntrests=data.return_array.userIntrests;
				$('#interest_popup').modal('hide');
			}).error(function(data, status, headers, config) {
				
				$("#profile_dialog").html("<?php echo $this->translate('Error occurred. Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog();
			});
		};	
		$scope.categoryHover = function(category_id){  
			$scope.HoverCategory = category_id;
		}
		$scope.categoryReset = function(){  
			$scope.HoverCategory = 0;
		}
		
	});		 
	app.directive('removeOnClick', function() {
		return {
			link: function(scope, elt, attrs) {
				scope.remove = function() {
					elt.remove();
				};
			}
		}
	});
	$(function() {
		if(profile.profile_photo!=''&&profile.profile_photo!=null){
			$('.image-editor').cropit({
				exportZoom: 1.25,
				imageBackground: true,
				imageBackgroundBorderWidth: 20,
				imageState: {
					src: '<?php echo $this->basePath(); ?>/public/datagd/profile/'+profile.user_id+'/'+profile.profile_photo
				}
			});
		}else if(profile.user_fbid!=''&&profile.user_fbid!=null){
			var imageUrl = 'https://graph.facebook.com/'+profile.user_fbid+'/picture?width=450&&height=450';
			convertImgToBase64(imageUrl, function(base64Img){
				$('.image-editor').cropit({
					exportZoom: 1.25,
					imageBackground: true,
					imageBackgroundBorderWidth: 20,
					imageState: {
					src:base64Img
					}
				});
			});			
		}else{
			$('.image-editor').cropit({
				exportZoom: 1.25,
				imageBackground: true,
				imageBackgroundBorderWidth: 20,
				imageState: {
					src: '<?php echo $this->basePath(); ?>/public/images/profile-default-crop.jpg'
				}
			});
		}
        $('.export').click(function() {
			var imageData = $('.image-editor').cropit('export');
			window.open(imageData);
        });		
    });
	function convertImgToBase64(url, callback, outputFormat){
		var canvas = document.createElement('CANVAS');
		var ctx = canvas.getContext('2d');
		var img = new Image;
		img.crossOrigin = 'Anonymous';
		img.onload = function(){
			canvas.height = img.height;
			canvas.width = img.width;
			ctx.drawImage(img,0,0);
			var dataURL = canvas.toDataURL(outputFormat || 'image/png');
			callback.call(this, dataURL);
			// Clean up
			canvas = null; 
		};
		img.src = url;
	}
	var profilepic = [];
	$(document).on('change','#profile_image_file_edit',function(e){			  
		fileInput = e.target.files;
		profilepic = fileInput[0];
		moveProfilepictoTemp(); 	 
	});	
	function moveProfilepictoTemp(){
		var formData = new FormData();	
		var url = baseurl+'/user/uploadhandler';
		formData.append("mediaImage",profilepic);
		//$("#ImageUploadStatus").html('<img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif" />');	
		//document.getElementById("imgUserImage").src='<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif';
		$("#edit_profilepic_process").html('<div class="progress_status"></div>');
		$.ajax({
			type: 'POST',
			url: url,
			data: formData,
			cache: false,		 
			contentType: false,
			processData: false,	 
			success: function(response) {
				//$("#ImageUploadStatus").html('');
				$("#edit_profilepic_process").html('');
				if(response.return_array.process_status == 'success'){ 
					$('.image-editor').cropit('imageSrc', response.return_array.image_url); 
				}else{	
					$("#profile_dialog").html(response.return_array.process_info);
					$( "#profile_dialog" ).dialog();					 
				}	
			},
			error: function(xhr, ajaxOptions, thrownError) {		 			
				$("#profile_dialog").html("<?php echo $this->translate('upload failed.Please try again','default'); ?>");
				$( "#profile_dialog" ).dialog(); 
			}		
		});
	}
	$(document).on("click","#profile_image_edit",function(){
		if(profile.profile_photo!=''&&profile.profile_photo!=null){
			$('.image-editor').cropit('imageSrc', '<?php echo $this->basePath(); ?>/public/datagd/profile/'+profile.user_id+'/'+profile.profile_photo);		 
		}else if(profile.user_fbid!=''&&profile.user_fbid!=null){
			var imageUrl = 'https://graph.facebook.com/'+profile.user_fbid+'/picture?width=450&&height=450';			
			convertImgToBase64(imageUrl, function(base64Img){
				$('.image-editor').cropit('imageSrc',base64Img);		 
			});			
		}else{
			$('.image-editor').cropit('imageSrc','<?php echo $this->basePath(); ?>/public/images/profile-default-crop.jpg');			 
		}
		var dropbox = document.getElementById("profile_pic_editor_profile");
		// init event handlers
		dropbox.addEventListener("dragenter", dragEnterEdit, false);
		dropbox.addEventListener("dragexit", dragExitEdit, false);
		dropbox.addEventListener("dragover", dragOverEdit, false);
		dropbox.addEventListener("drop", dropEdit, false);
	 
	});
	function dragEnterEdit(evt) {
		evt.stopPropagation();
		evt.preventDefault();
	}
	function dragExitEdit(evt) {
		evt.stopPropagation();
		evt.preventDefault();
	}
	function dragOverEdit(evt) {
		evt.stopPropagation();
		evt.preventDefault();
	}
	function dropEdit(evt) {  
		evt.stopPropagation();
		evt.preventDefault();
		var files = evt.dataTransfer.files;		
		//if (navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1) {alert(1);alert(evt.target.files[0].name);$("#imgUserImage").html(files.name);}		
		var count = files.length;
		// Only call the handler if 1 or more files was dropped.
		if (count > 0)
			handleFilesEdit(files);
	}
	function handleFilesEdit(files) {
		var file = files[0];		 
		profilepic = files[0];
		moveProfilepictoTemp(); 
		//var reader = new FileReader();	 
		//reader.onloadend = handleReaderLoadEnd; 
		//reader.readAsDataURL(file);
	}
	function handleReaderProgress(evt) {
		if (evt.lengthComputable) {
			var loaded = (evt.loaded / evt.total);
			$("#progressbar").progressbar({ value: loaded * 100 });
		}
	}
	function handleReaderLoadEnd(evt) {
		var img = document.getElementById("imgUserImage");
		img.src = evt.target.result;
		$("#default_img").hide();
		$("#uploaded_img").show();	 
	}
</script>