<?php 
	if($locales_selected=='ar_AE'){
		$language_class="ar";
	}else{
		$language_class="en";
	}	 
?>
 <div class="feed-filter_outer sub_top-margin">
    	<div class="home-container">
        	<h1> <i class="back-button"></i> <?php echo $this->translate('Settings','default'); ?></h1>
        </div>
    </div>
    
    <div class="home-container feeds-container <?php echo $language_class; ?>"  id="setting_container" ng-controller="settingController" ng-cloak>
    	<div class="filter_sub-outer">
        	<div class="row">
            	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="show-sorting">
                        <span><a href="javascript:void(0);" ng-class="{'active':activeTab == 'account'}" id="account_tab" ng-click="activeTab = 'account'"><?php echo $this->translate('Account','default'); ?></a></span>
                        <span><a href="javascript:void(0);" id="notification_tab" ng-class="{'active': activeTab == 'notification'}" ng-click="activeTab = 'notification'"><?php echo $this->translate('Notifications','default'); ?></a></span>
                        <span><a href="javascript:void(0);" id="password_tab" ng-class="{'active': activeTab == 'password'}" ng-click="activeTab = 'password'"><?php echo $this->translate('Password','default'); ?></a></span>
						<span><a href="javascript:void(0);" id="password_tab" ng-class="{'active': activeTab == 'Language'}" ng-click="activeTab = 'Language'"><?php echo $this->translate('Language','default'); ?></a></span>
                    </div>
                </div>
                
                <div class="clear"></div>
            </div>
        </div>
            
        <div class="account_settings-outer border_radius">
				
        	<div id="account_settings" ng-if="activeTab=='account'">
                <div class="setting_label"><?php echo $this->translate('Username','default'); ?></div>
                <div class="setting_field">
				<input name="username" type="text" ng-model="user.username" required/>
				<span style="color:red" ng-if="username_error"><?php echo $this->translate('User name required','default'); ?></span>
				</div>
                <div class="clear"></div>
                <div class="setting_label"><?php echo $this->translate('Email','default'); ?></div>
                <div class="setting_field"><input name="email" ng-model="user.user_email" type="text"  required/>
				<span style="color:red" ng-if="email_error"><?php echo $this->translate('Email required','default'); ?></span>
				</div>
                <div class="clear"></div>
                <div class="setting_label"><?php echo $this->translate('Timezone','default'); ?></div>
                <div class="setting_field fixed-search profile-edit_search timezone_edit">
					
					<a id="dLabel_settings" data-toggle="dropdown" class="" href="javascript:void(0);">{{user_selected_timezone}}</a>
					
					<ul aria-labelledby="dLabel_settings" role="menu" class="dropdown-menu timezone_dropdown" style="top:40px;width:98%" >
						<div id="timzone_list" ng-init="enableScrollBar()" style="position:relative">
						<li ng-repeat="item in timezonelist"><a href="javascript:void(0)" ng-click="showDropdown(item.timezone_id,item.timezone)" >{{item.timezone}}</a></li>
						</div>
					</ul>	
					 			 
				</div>				
				 
                <div class="clear"></div>
                <div class="setting_label"><?php echo $this->translate('Phone','default'); ?></div>
                <div class="setting_field"><input name="phone" maxlength="11" minlength="11" type="text" ng-model="user.phone"  /></div>
                <div class="clear"></div>
				<div ng-if="accountAjax==1"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"></div>
                <div class="setting_save-butn" ng-if="accountAjax!=1"><a href="javascript:void(0);" class="default_butn_blue" ng-click="saveProfile()"><?php echo $this->translate('Save','default'); ?></a></div>
            </div>
            <div ng-if="activeTab=='notification'">
            	<div class="setting_label"><?php echo $this->translate('Notify Me When','default'); ?></div>
                <div class="setting_checkboxes" id="notifymelist">
					<ul class="notify_list">
						<li ng-repeat="item in notifymelist"><a href="javascript:void(0)" ng-click="selectNotifyList(item.notify_id)">
						<i class="check_blue" ng-if="!checkInList(item.notify_id)"></i>
						<i class="check_blue_checked" ng-if="checkInList(item.notify_id)"></i>
						{{item.notify_content_locale}}</a></li>
					</ul>
					 
                                                  
				</div>
                <div class="clear"></div>
                <div class="setting_label"><?php echo $this->translate('Email Me When','default'); ?></div>
                <div class="setting_checkboxes" id="emailmelist">
					<ul class="notify_list">
						<li ng-repeat="item in emailmelist"><a href="javascript:void(0)" ng-click="selectEmailmeList(item.emailme_id)">
						<i class="check_blue" ng-if="!checkInEmailList(item.emailme_id)"></i>
						<i class="check_blue_checked" ng-if="checkInEmailList(item.emailme_id)"></i>
						{{item.emailme_content_locale}}</a></li>
					</ul>                        
				</div>
                <div class="clear"></div>
				<div ng-if="notificationAjax==1"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"></div>
                <div class="setting_save-butn" ng-if="notificationAjax!=1"><a href="javascript:void(0);" class="default_butn_blue"ng-click="saveNotification()" ><?php echo $this->translate('Save','default'); ?></a></div>
                
            </div>
            
            <div id="password_settings" ng-if="activeTab=='password'">
                <div class="setting_label"><?php echo $this->translate('Current Password','default'); ?></div>
                <div class="setting_field"><input required name="currentPassword" id="currentPassword" type="password"   ng-model="user.currentPassword" />  
				<span style="color:red" ng-if="currentPassword_error"><?php echo $this->translate('Current Password required','default'); ?></span>				
                </div>
                <div class="clear"></div>
                <div class="setting_label"><?php echo $this->translate('New Password','default'); ?></div>
                <div class="setting_field"><input required name="newPassword" id="newPassword" type="password" ng-model="user.newPassword"/>
				<span style="color:red" ng-if="newPassword_error"><?php echo $this->translate('New Password required','default'); ?></span>
				</div>
                <div class="clear"></div>
                <div class="setting_label"><?php echo $this->translate('Confirm Password','default'); ?></div>
                <div class="setting_field"><input required name="confirmPassword" id="confirmPassword" type="password" ng-model="user.confirmPassword" />
				<span style="color:red" ng-if="confirmPassword_error"><?php echo $this->translate('New Password and  Confirm Password must be same','default'); ?></span>	
				</div>
                <div class="clear"></div>
				<div ng-if="passwordAjax==1"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"></div>
                <div class="setting_save-butn" ng-if="passwordAjax!=1"><a href="javascript:void(0);" class="default_butn_blue" ng-click="savePassword(user)"><?php echo $this->translate('Save','default'); ?></a></div>
            </div>
            <div id="password_settings" ng-if="activeTab=='Language'">
				<div>
					<?php 
					if($locales_selected == ''){ ?>
						<a href="javascript:void(0)" id="default_locale">English</a>
					<?php }else{
						foreach($locales as $lang){
							if($lang->locales_code == $locales_selected){
								echo '<a href="javascript:void(0)" id="default_locale">'.$lang->locales_name.'</a>';
							}
						}
					} ?>
					<div id="locale_list" style="display:none">
						<?php foreach($locales as $lang){ 
								echo ' <a href="javascript:void(0)" class="select_locale" data-item="'.$lang->locales_code.'">'.$lang->locales_name.'</a> ';
							 
						} ?>
					</div>
					<div id="localeajaxloader" style="display:none;"><center><img src="<?php echo $this->basePath();?>/public/images/ajax_loader.gif" /></center></div>  
				</div>
			</div>
        </div>
        
        <div class="clear"></div>
    </div>
	 <div id="settings_dialog" title="" style="display:none" class="common_error"></div>
	<style>
		.active{
			display:block;
		}
	</style>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/public/js/jquery.slimscroll.js"></script>
<script type="text/javascript" src='<?php echo $this->basePath(); ?>/public/js/jquery-customSelect.js'></script>
<script type="text/javascript">
	
	var profile = <?php echo json_encode($profile_data); ?>; 
		var settingapp = angular.module('settingapp',[]);
		settingapp.config(function ($httpProvider) {
			$httpProvider.defaults.transformRequest = function(data){
				if (data === undefined) {
					return data;
				}
				return $.param(data);
			}
		});
		settingapp.controller('settingController',function($scope, $http){ 
			$scope.user = {};
			$scope.profile = <?php echo json_encode($profile_data); ?>; 
			$scope.user.username = $scope.profile.user_given_name;
			$scope.user.user_email = $scope.profile.user_email;
			$scope.user.phone = $scope.profile.user_profile_phone
			$scope.user.timezoneID = $scope.profile.user_timezone_id;
			$scope.timezonelist = <?php echo json_encode($timezones); ?>;
			$scope.activeTab = "account" ;
			$scope.notifymelist= <?php echo json_encode($notifyContent); ?>;
			$scope.emailmelist=<?php echo json_encode($emailmecontent); ?>;	
			$scope.username_error = 0;
			$scope.email_error = 0;
			$scope.selectedNofication = [<?php echo $user_notify_me_content; ?>];
			$scope.selectedEmailme = [<?php echo $user_email_me_content; ?>];
			$scope.accountAjax = 0;
			$scope.drpClass = "dropdown_close";
			$scope.isVisible =0;
			$scope.user_selected_timezone = '<?php echo $this->translate('Please select Timezone','default'); ?>';
			if($scope.user.timezoneID>0){
				angular.forEach($scope.timezonelist, function(dataset){ 
					 if($scope.user.timezoneID==dataset.timezone_id){
						 $scope.user_selected_timezone = dataset.timezone;
					 }
				});
			}
			$scope.saveProfile = function(){
				var error = 0;
				if($scope.user.username==''||$scope.user.username=='undefined'||$scope.user.username==undefined){
					error++;
					$scope.username_error = 1;
				}
				if($scope.user.user_email==''||$scope.user.user_email=='undefined'||$scope.user.user_email==undefined){
					error++;
					$scope.email_error = 1;
				}
				if(!validateEmail($scope.user.user_email)){
					error++;
					$scope.email_error = 1;
				}
				if(error==0){
					$scope.accountAjax = 1;
					url  = baseurl+'/user/savesettings';
					$http.post(url,
					{
						user_name:$scope.user.username,
						user_email:$scope.user.user_email,
						timezone:$scope.user.timezone,
						phone:$scope.user.phone,
						settings_type:'account'
					}
					, {headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
					).success(function(data, status, headers, config) {
						$scope.accountAjax =0;
						if(data.return_array.process_status == 'success'){					
						//window.location.reload();	
							$("#settings_dialog").html("<?php echo $this->translate('Successfully updated your profile details','default'); ?>");	
							$("#settings_dialog").dialog();
						}else{
							$("#settings_dialog").html(data.return_array.process_info);							 
							$("#settings_dialog").dialog();
						}				     
					}).error(function(data, status, headers, config) {
						$("#settings_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");
												 
							$("#settings_dialog").dialog();
						$scope.accountAjax =0;
					});
				}
			}
			$scope.selectNotifyList = function(notify_id){
				var index = $scope.getArrayIndex($scope.selectedNofication,notify_id);			 
				if(index>=0) {
					$scope.selectedNofication.splice( index, 1 );			
				} else {
					$scope.selectedNofication.push(notify_id);			
				}
				
			}
			$scope.checkInList = function(notify_id){
				 var index =  $scope.getArrayIndex($scope.selectedNofication,notify_id);
				 if(index>=0){
					return true;
				 }else{return false;}
			}
			$scope.checkInEmailList = function(email_id){
				 var index =  $scope.getArrayIndex($scope.selectedEmailme,email_id);
				 if(index>=0){
					return true;
				 }else{return false;}
			}
			
			$scope.selectEmailmeList = function(email_id){
				var index = $scope.getArrayIndex($scope.selectedEmailme,email_id);			 
				if(index>=0) {
					$scope.selectedEmailme.splice( index, 1 );			
				} else {
					$scope.selectedEmailme.push(email_id);			
				}			
			}
			$scope.notificationAjax = 0;
			$scope.saveNotification = function(){
				url  = baseurl+'/user/savesettings';
				$scope.notificationAjax = 1;
				$http.post(url,
				{
					EmailmeId:$scope.selectedEmailme,
					NotifymeId:$scope.selectedNofication,					 
					settings_type:'notification'
				}
				, {headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
				).success(function(data, status, headers, config) {
					$scope.notificationAjax = 0;
					if(data.return_array.process_status == 'success'){					
						$("#settings_dialog").html("<?php echo $this->translate('Successfully updated your profile settings','default'); ?>");	
						$("#settings_dialog").dialog();				
					}else{
						$("#settings_dialog").html(data.return_array.process_info);							 
						$("#settings_dialog").dialog();
					}				     
				}).error(function(data, status, headers, config) {
					$("#settings_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");					 					 
					$("#settings_dialog").dialog();
					$scope.notificationAjax = 0;
				});
			}
			$scope.currentPassword_error = 0;
			$scope.newPassword_error = 0;
			$scope.confirmPassword_error = 0;
			$scope.passwordAjax = 0;
			$scope.savePassword = function(){
				url  = baseurl+'/user/savesettings';
				var error = 0;
				if($scope.user.currentPassword==''||$scope.user.currentPassword==undefined){
					error++;
					$scope.currentPassword_error = 1;
				}
				if($scope.user.newPassword==''||$scope.user.newPassword==undefined){
					error++;
					$scope.newPassword_error = 1;
				}
				if($scope.user.confirmPassword==''||$scope.user.confirmPassword==undefined){
					error++;
					$scope.confirmPassword_error = 1;
				}
				if($scope.user.confirmPassword!= $scope.user.newPassword==undefined){
					error++;
					$scope.confirmPassword_error = 1;
				}
				if(error==0){
					$scope.passwordAjax = 1;
					$scope.currentPassword_error = 0;
					$scope.newPassword_error = 0;
					$scope.confirmPassword_error = 0;
					$http.post(url,
					{					 
						current_password:$scope.user.currentPassword,
						user_password:$scope.user.newPassword,							
						settings_type:'password'
					}
					, {headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
					).success(function(data, status, headers, config) {						 
						$scope.passwordAjax = 0;
						if(data.return_array.process_status == 'success'){					
							$("#settings_dialog").html("<?php echo $this->translate('Successfully updated your password','default'); ?>.");							 		 					 
							$("#settings_dialog").dialog();
							
							//window.location.reload();
						}else{
							$("#settings_dialog").html(data.return_array.process_info);						 							 		 					 
							$("#settings_dialog").dialog();
						}				     
					}).error(function(data, status, headers, config) {
						$("#settings_dialog").html("<?php echo $this->translate('Error occured. Please try again','default'); ?>");					 					 
						$("#settings_dialog").dialog();
						$scope.passwordAjax = 0;
					});
				}
			}
			$scope.getArrayIndex = function(arr_elemnt,item){ 
				var incexist = -1;
				for(i=0;i<arr_elemnt.length;i++) {
					if(arr_elemnt[i] == item){incexist = i;}
				}
				return incexist;
			}; 
			$scope.showDropdown = function(id,timezonevalues){
				 
				$scope.user.timezoneID = id,
				$scope.user.timezone = id,
			 
				 $scope.user_selected_timezone = timezonevalues;
				 
			}
			$scope.enableScrollBar = function(){
			 $('#timzone_list').slimScroll({
				  color: '#00f',height:'250px'
			  });
			}
		});		 

	 angular.element(document).ready(function() {
	 angular.bootstrap(document.getElementById("setting_container"), ["settingapp"]);	 
	
	 
});
function validateEmail($email) {
  var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
  if( !emailReg.test( $email ) ){ return false; } else { return true; }
}  	
 $(document).on("click","#default_locale",function(){ $("#locale_list").toggle(); });
 $(document).on("click",".select_locale",function(){ 
		var selected_locale = $(this).attr("data-item");
		var urls = "<?php echo $this->basePath(); ?>/setUserLocale";
		var data = {selected_locale: selected_locale};
		$.ajax({
			type:'POST',
			url: urls, 
			data: data, 
			beforeSend:function(){  
				$('div#localeajaxloader').show();
				isAjaxRunning = 1; 
			},
			success: function(response) {
				$('div#localeajaxloader').hide();
				if(response.return_array.process_status == 'success'){
					window.location.reload();
				}else{
					$("#settings_dialog").html(response.return_array.process_info);
					$("#settings_dialog").dialog();
				}				 
			},
			error: function(resp) { $("#settings_dialog").html(resp.responseText);
					$("#settings_dialog").dialog(); }
		});
	});
</script>