	<?php 
	if($locales_selected=='ar_AE'){
		$language_class="ar";
	}else{
		$language_class="en";
	}	 
?>
<!-- Left Fixed part -->
<?php echo $this->profileWidget; ?>
<!-- Left Fixed part Close -->
<div id="group_right_container" ng-app="groupapp" ng-controller="groupController" ng-switch on="profileData.switch"  ng-cloak>
    <div class="right_container <?php echo $language_class; ?>">
    	<div class="right-profile_links">
        	<div class="right-profile_links_inner">
            	<ul class="color-trans">
                	<li><a href="<?php echo $this->basePath()."/".$current_Profile ?>"><?php echo $this->translate('Posts','default'); ?></a></li>
                    <li><a href="<?php echo $this->basePath()."/".$current_Profile ?>/groups" class="active" ><?php echo $this->translate('Groups','default'); ?>  ({{group_count}})</a></li>
                    <li><a href="<?php echo $this->basePath()."/".$current_Profile ?>/friends"><?php echo $this->translate('Friends','default'); ?> ({{frineds_count}})</a></li>
					<?php if($myprofile==1){ ?>
                    <li><a href="<?php echo $this->basePath()."/".$current_Profile ?>/activities"><?php echo $this->translate('My Activity','default'); ?></a></li>
					<?php } ?>
                </ul>
            </div>
        </div>
        <div class="right-content_outer">
        	<div class="friends_sort">
            	<div class="group_sort color-trans">
                    <?php echo $this->translate('Show','default'); ?>:
                    <a href="javascript:void(0);" ng-class="{'active':selectedType == 'All'}" ng-click="showAll()" ><?php echo $this->translate('All','default'); ?></a>
                    <a href="javascript:void(0);" ng-class="{'active':selectedType == 'created'}" ng-click="showCreated()"><?php echo $this->translate('Created','default'); ?> ({{created_group_count}})</a>
					<a ng-if="myprofile!=1" href="javascript:void(0);" ng-class="{'active':selectedType == 'mutual'}" ng-click="showMutual()"><?php echo $this->translate('Mutual','default'); ?>({{mutual_group_count}})</a>
                    <a href="javascript:void(0);" ng-class="{'active':selectedType == 'joined'}" ng-click="showJoined()"><?php echo $this->translate('Joined','default'); ?> ({{joined_group_count}})</a>
                    <a ng-if="myprofile==1" href="javascript:void(0);" ng-class="{'active':selectedType == 'pending'}" ng-click="showPending()"><?php echo $this->translate('Pending Requests','default'); ?>  ({{pending_group_count}})</a>
                </div>
				<div class="create_group">
					<a data-target="#create_group" data-toggle="modal" class="default_butn_violet" href="javascript:void(0);"  id="group_creat_butn"><?php echo $this->translate('Create New Group','default'); ?> </a>
				</div>
				<div class="clear"></div>
            </div>
            <div class="row" scroller ng-init="showGroups(false);">
				<div ng-if="ajaxFlag==1&&page==1"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"></div>
                <div ng-if="ajaxFlag==0||page>1" class="col-lg-4 col-md-4 col-sm-6 col-xs-12" ng-repeat="items in group_list">
                    <div class="group-list-outer <?php echo $language_class; ?>">
                        <div class="group-img_head">
							 <div class="own_group-label" ng-if="items.is_admin==1" >
                            	<div class="owner_profile">
                                	<img alt="" ng-if="profile.profile_photo!=null&&profile.profile_photo!=''" src="<?php echo $this->basePath(); ?>/public/datagd/profile/{{profile.user_id}}/{{ profile.profile_photo }}">
									<img alt="" ng-if="(profile.profile_photo==null||profile.profile_photo=='')&&(profile.user_fbid!=null&&profile.user_fbid!='')" src="https://graph.facebook.com/{{profile.user_fbid}}/picture?width=66&&height=66">
									<img alt="" ng-if="(profile.profile_photo==null||profile.profile_photo=='')&&(profile.user_fbid==null||profile.user_fbid=='')" src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg">
                                    <span class="owner-badge"></span>
                                </div>
                            </div>
                            <img ng-if="items.group_photo_photo!=''&&items.group_photo_photo!=null" src="{{groupImagePath}}{{items.group_id}}/medium/{{items.group_photo_photo}}" alt="" />
							<img ng-if="items.group_photo_photo==''||items.group_photo_photo==null" src="<?php echo $this->basePath(); ?>/public/images/group-img_def.jpg" alt="" />
                            <div class="group-shadow"><a href="<?php echo $this->basePath(); ?>/groups/{{items.group_seo_title}}"></a></div>
                            <div class="join-group-butn">
								<a class="button_corner_grey" href="javascript:void(0);" ng-if="items.group_status =='pending'"><?php echo $this->translate('Pending Approval','default'); ?></a>
								<a class="button_corner_yellow" href="<?php echo $this->basePath(); ?>/groups/{{items.group_seo_title}}?edit=1" ng-if="items.group_status !='pending' && items.is_admin==1"><?php echo $this->translate('Edit Group','default'); ?></a>
								<!-- <a class="button_corner_red" href="javascript:void(0);" ng-if="items.group_status !='pending' && items.is_admin!=1&&items.is_member==1" data-toggle="modal" data-target="#confirm_popup" ng-click="selectLeavingGroup(items.group_id,items.group_title)">Leave This Group</a>	-->							
								<a class="button_corner_blue" href="javascript:void(0);" ng-if="items.group_status !='pending' && items.is_admin!=1&&items.is_member!=1&&items.group_type !='private'&&items.is_requested!=1" data-toggle="modal" data-target="#join_group" ng-click="selectJoiningGroup(items.group_id,items.group_title,items.group_type,items.group_seo_title)"><?php echo $this->translate('Join This Group','default'); ?></a>
								<a class="button_corner_grey" href="javascript:void(0);" ng-if="items.group_status !='pending' && items.is_admin!=1&&items.is_member!=1&&items.group_type !='private'&&items.is_requested==1"><?php echo $this->translate('Already requested','default'); ?></a>
								<a class="button_corner_blue" href="javascript:void(0);" ng-if="items.group_status !='pending' && items.is_admin!=1&&items.is_member!=1&&items.group_type =='private'&&items.is_invited==1"data-toggle="modal" data-target="#join_group" ng-click="selectJoiningGroup(items.group_id,items.group_title,items.group_type,items.group_seo_title)"><?php echo $this->translate('Join This Group','default'); ?></a>
							</div>
                            <div class="group-titles">
                               <a href="<?php echo $this->basePath(); ?>/groups/{{items.group_seo_title}}"> {{items.group_title}}</a>
                                <span ng-if="items.group_type =='open'">
                                <i class="group-open"></i><!-- Change the <i> class when chenge the group privacy -->
                               <?php echo $this->translate('Open Group','default'); ?>
								</span>
								<span ng-if="items.group_type =='private'">
									<i class="group-private"></i><!-- Change the <i> class when chenge the group privacy -->
									<?php echo $this->translate('Private Group','default'); ?>
								</span>
								<span ng-if="items.group_type =='public'">
									<i class="group-public"></i><!-- Change the <i> class when chenge the group privacy -->
									<?php echo $this->translate('Public Group','default'); ?>
								</span>
                            </div>
                        </div>
                        <div class="group-body">
                            <div class="group-interest_location">
                                <div class="group_interest"><?php echo $this->translate('Group Interests','default'); ?></div>
                                <div class="group_location"><i class="group-location"></i>{{items.city_locale}}, {{items.country_locale}}</div>
                                <div class="clear"></div>
                            </div>
                            <div class="group-category_icons">                  	 
								<img  alt="" ng-repeat="tagitem in items.tag_category" ng-if="tagitem.tag_category_icon!=''&&$index<=3" src="{{categoryImagePath}}{{tagitem.tag_category_icon}}" alt="{{tagitem.tag_category_title}}" />
								<img ng-repeat="tagitem in items.tag_category" ng-if="tagitem.tag_category_icon==''&&$index<=3" src="<?php echo $this->basePath(); ?>/public/images/category-icon.svg" alt="{{tagitem.tag_category_title}}" /> 
								<span class="interest_more" ng-if="items.tag_category_count>4">+{{ items.tag_category_count- 4 }}</span>                        
							</div>
                            <div class="group-interest_list">
								<span ng-repeat="tags in items.tags" ng-if="checkCommonIntrests(tags.tag_id)" style="text-transform:capitalize;" class="interest_common"> {{tags.tag_title_locale}}<i>.</i></span>
								<span ng-repeat="tags in items.tags" ng-if="!checkCommonIntrests(tags.tag_id)" style="text-transform:capitalize;"> {{tags.tag_title_locale}}<i>.</i></span>
							</div>
							<div class="group_members-friends">
								<div class="group_members"><?php echo $this->translate('members','default'); ?>: <span>{{items.member_count}}</span></div>
								<div class="group_friends"  ng-if="items.is_admin!=1" ><?php echo $this->translate('friends','default'); ?>: 
									<span ng-if="items.friend_count>0"><a href="javascript:void(0)" ng-mouseover="loadToolTip(items.group_id)" ng-mouseout="unloadToolTip(items.group_id)" ng-click="LoadFriendsUsers(items.group_id,1,items.friend_count)" >{{items.friend_count}}</a></span>
									<span ng-if="items.friend_count<=0">0</span>
									<div ng-if="items.friend_count>0" class="like_tooltip tooltip_friends" id="tooltip_{{items.group_id}}" style="display:none">
										<span ng-repeat="frienduser in items.friends">{{frienduser.user_given_name}}</span>
										<span ng-if="items.friend_count>2"><?php echo $this->translate('More','default'); ?>..</span>					 
									</div> 
								</div>
								<div class="group_friends"  ng-if="items.is_admin==1" ><?php echo $this->translate('new Requests','default'); ?>: <span>{{items.request_count}}</span></div>
								<div class="clear"></div>
							</div>
                        </div>
                    </div>
                </div>
			</div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="pop_bg modal fade" id="create_group" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog group_popup" ng-init="loadFirstFrom()">
        <div class="modal-content create_group_outer <?php echo $language_class; ?>">
			<div class="modal-header create_group-head">
				<div class="create_group-header">
					<div class="level-1" ng-class="{active:selectedFrom == 'level1'}">
						1<i></i><?php echo $this->translate('Group Info','default'); ?>
					</div>
					<div class="level-2" ng-class="{active:selectedFrom == 'level2'}">
						2<i></i><?php echo $this->translate('Interests','default'); ?>
					</div>
					<div class="level-3" ng-class="{active:selectedFrom == 'level3'}">
						3<i></i><?php echo $this->translate('INVITE &amp; ASK','default'); ?>
					</div>
				</div>
				<button type="button" class="close" data-dismiss="modal" ng-click="removeData();"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo $this->translate('Close','default'); ?></span></button>
				<div class="clear"></div>
			</div>
			<div class="modal-body signup_body">
				<div id="signup_step1">                 
					<div class="step1_outer" ng-if="selectedFrom == 'level1'">
                        <div class="create_group-label"><?php echo $this->translate('Name Your Group','default'); ?>*</div>
                        <div class="login-field">
							<input name="name" type="text" placeholder="<?php echo $this->translate('e.g. Arsenal Lovers','default'); ?>" ng-model="mygroup.groupTitle" />
							<span ng-show="groupTitileError" style="color:red"><?php echo $this->translate('Group name is required','default'); ?>.</span>
                        </div>
                        <div ng-show="Locationloading" class="loading"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> </div>
                        <div class="group_select_col-left" id="CountryDropDown">
							<div class="create_group-label"><?php echo $this->translate('Choose Group Country','default'); ?></div>
							<div class="fixed-search profile-edit_search" >
								<a id="dLabel_country" href="javascript:void(0)" data-toggle="dropdown"  >{{country_title}}</a>
								<ul class="color-trans dropdown-menu border_radius " aria-labelledby="dLabel_country" role="menu">
									<li  ng-repeat="item in country" ng-click="showCountryDropdown(item.country_id,item.country_title_locale)"  ><a href="javascript:void(0);">{{item.country_title_locale}}</a></li>					 			
								</ul>							 
							</div>							 
						</div>
						<div class="group_select_col-right" id="CityDropDown">
							<div class="create_group-label"><?php echo $this->translate('Choose Group City','default'); ?></div>
							<div class="fixed-search profile-edit_search cityDropdown" >
								<a id="dLabel_city" href="javascript:void(0)" data-toggle="dropdown"  >{{city_selected}}</a>
								<ul class="color-trans dropdown-menu border_radius" aria-labelledby="dLabel_city" role="menu">					
									<li  ng-repeat="item in city" ng-click="showCityDropdown(item.city_id,item.city_locale)" ><a href="javascript:void(0);">{{item.city_locale}}</a></li>					 			
								</ul>
							</div>
						</div>
                        <div class="clear"></div>
                         <!-- The file input-button span is used to style the file input field as button -->
                        <div class="create_group-label" ><?php echo $this->translate('Upload Banner Photo','default'); ?></div>
						<div class="drag_drop-media group_drag-drop" id="uplodbtn">						 
							<div class="drag-caption"  > 
								<center><div id="ImageUploadStatus"></div></center> 
								<div id="default_img" onClick="getFile()"> 
									<img src="<?php echo $this->basePath();?>/public/images/drag_drop-img.svg" alt=""   /> 
									<br /><?php echo $this->translate('Choose a photo to upload','default'); ?> 
								</div> 
								<div id="uploaded_img" style="display:none"> 
									<img src="<?php echo $this->basePath();?>/public/images/drag_drop-img.svg" alt="" id="imgUserImage" /> 
									<a href="javascript:void(0)" id="removeUploaded" class="media_upload_close"><?php echo $this->translate('Close','default'); ?> </a> 
								</div> 
								<input type="file" name="btnUploadImage" id="btnUploadImage" style="width:0;height:0"  >                                
							</div>	
						</div>						
						<div id="uploadPreview"></div>
						<div id="progress">	</div>
						<div id="image_error"></div>
                        <div class="create_group-label"><?php echo $this->translate('Choose Group Type','default'); ?></div>
                        <div class="select_group-type">
                            <input type="radio" name="group_type" id="open-group" value="1" ng-model="mygroup.grouptype">
                            <label for="open-group">
                                    <i class="radio-styled"></i>
                                    <i class="group-open_black"></i><?php echo $this->translate('Open Group','default'); ?>
                            </label>
                            <div class="group-type_details">
								<?php echo $this->translate("This group will be visible to everyone and can be joined immediately",'default'); ?>   <br />
								(<?php echo $this->translate("without group owner approval",'default'); ?>).
							</div>
                            <div class="clear"></div>
                        </div>
                        <div class="select_group-type">
                            <input type="radio" name="group_type" id="Public-group"  value="2" ng-model="mygroup.grouptype">
                            <label for="Public-group">
                                    <i class="radio-styled"></i>
                                    <i class="group-public_black"></i><?php echo $this->translate("Public Group",'default'); ?>
                            </label>
                            <div class="group-type_details">
								<?php echo $this->translate("This group will be visible to everyone, but the group owner receives requests for the group joining which he can accept or decline.",'default'); ?>
							</div>
                            <div class="clear"></div>
                        </div>
                        <div class="select_group-type">
                            <input type="radio" name="group_type" id="closed-group"  value="3" ng-model="mygroup.grouptype">
                            <label for="closed-group">
                                    <i class="radio-styled"></i>
                                    <i class="group-private_black"></i><?php echo $this->translate("Private Group",'default'); ?>
                            </label>
                            <div class="group-type_details">
								<?php echo $this->translate("This group will not be visible to anyone in regular search. It is invite based and users can not join the group unless you invite them.",'default'); ?>
								.
							</div>
                            <div class="clear"></div>
                        </div>
                        <div class="create_group-label"><?php echo $this->translate("Describe Your Group",'default'); ?>*</div>
                        <div class="login-field">
							<textarea name="discribe_group" placeholder="<?php echo $this->translate("Tell us what is your group about",'default'); ?>"  ng-model="mygroup.description"></textarea>
							<span ng-show="groupDescriptionError" style="color:red"><?php echo $this->translate("Group Description is required",'default'); ?>.</span>
						</div>
                        <div class="signup_button">                        
							<div class="signup-link"><a href="javascript:void(0);" class="default_butn_normal" ng-click="clearForms()"><?php echo $this->translate("Cancel",'default'); ?></a> <a href="javascript:void(0);" class="default_butn_blue" id="go_step-2" ng-click="LoadSecondFrom()"><?php echo $this->translate("Continue",'default'); ?></a></div>
							<div class="clear"></div>
						</div>
                    </div>                    
				</div>              
				<div id="signup_step2"  ng-if="selectedFrom == 'level2'">
				   <div class="group_select_col-left">
						<div class="create_group-label"><?php echo $this->translate("Choose Category",'default'); ?></div>
						<div class="interest_category-outer dropdown_icons-outer group_dd-category" ng-switch on="groupintrest.switch" >
							<a id="dLabel_groupintrest" data-toggle="dropdown" class="" href="javascript:void(0);">
								<img ng-if="selectedGroupIntrestCategoryIcon!=''" src="{{categoryImagePath}}{{selectedGroupIntrestCategoryIcon}}" alt="{{selectedIntrestCategory}}" />
								<img ng-if="selectedGroupIntrestCategoryIcon==''" src="<?php echo $this->basePath(); ?>/public/images/category-icon.svg" alt="{{selectedIntrestCategory}}" /> 
								{{selectedGroupIntrestCategory}}
							</a>
							<ul class="color-trans dropdown_icons border_radius dropdown-menu" aria-labelledby="dLabel_groupintrest" role="menu"   ng-switch-when="1">
								<div ng-init="enableGroupIntrestScrollBar()" id="group_intrest_category_list">
									 
									<li   ng-repeat="item in groupCategory">
									<a href="javascript:void(0);" ng-click="selectGroupIntrestCategory(item.tag_category_id,item.tag_category_icon,item.tag_category_title_locale)">
									<img ng-if="item.tag_category_icon!=''" src="{{categoryImagePath}}{{item.tag_category_icon}}" alt="{{item.tag_category_title_locale}}" />
									<img ng-if="item.tag_category_icon==''" src="<?php echo $this->basePath(); ?>/public/images/category-icon.svg" alt="{{item.tag_category_title_locale}}" /> 
									{{item.tag_category_title_locale}}</a>
									</li>
								</div>
															 
							</ul>
							 
							<div ng-switch-when="2" class="loading"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> </div>
						</div>
					</div>
					<div class="group_select_col-right">
						<div class="create_group-label">&nbsp;</div>
						<div class="fixed-search interest_search">
						   <input type="text" placeholder="<?php echo $this->translate("Search Interest",'default'); ?>" name="search" ng-model="grouptag_search" >
							<a href="javascript:void(0);"></a>
						</div>
					</div>
					<div class="clear"></div>
					<div class="popup_interest-lists" ng-show="showgrouptags"  >
						<a class="interest_add" remove-on-click href="javascript:void(0);"    ng-repeat="items in filtered = (grouptags | filter:grouptag_search) | limitTo:group_tag_limit" ng-click="addToSelectedGroupIntrest(items.category_id,items.tag_id,items.tag_title_locale);remove()">{{items.tag_title_locale}}<span></span></a>	
						<a ng-show="showgroupmoretags" ng-click="increaseLimit(group_tag_limit)" ng-hide="filtered.length <= group_tag_limit">
							<?php echo $this->translate("More",'default'); ?>...
						</a>				
					</div>
					<div class="create_group-label"><?php echo $this->translate("Chosen Group Interests",'default'); ?></div>
					<div class="selected_interest">
					<img  ng-repeat="items in objSelectedGroupCategory"   ng-if="items.category_icon!=''" src="{{categoryImagePath}}{{items.category_icon}}" alt="{{items.category_title}}" />
					<img ng-repeat="items in objSelectedgroupCategory" ng-if="items.category_icon==''" src="<?php echo $this->basePath(); ?>/public/images/category-icon.svg" alt="{{items.category_title}}" /> </div>
					<div class="popup_interest-lists">
					<a class="interest_added" href="javascript:void(0);" ng-repeat="items in objSelectedGroupTags" remove-on-click ng-click="remove();removeFromSelectedGroupIntrest(items.tag_name,items.category)" >{{items.tag_name}}<span></span></a>
					 
					</div>
                <div style="color:red" ng-if="groupIntresetError"><?php echo $this->translate("Select some interests to proceed",'default'); ?></div>
				 
                <div class="signup_button">
                    <div class="signup-link"><a href="javascript:void(0);" class="default_butn_normal" id="go_step-1" ng-click="goback('level1')"><?php echo $this->translate("Back",'default'); ?></a> <a href="javascript:void(0);" class="default_butn_blue" id="go_step-3" ng-click="LoadThirdFrom()"><?php echo $this->translate("Continue",'default'); ?></a></div>
                    <div class="clear"></div>
                </div>
            </div>             

            <div id="signup_step3" ng-if="selectedFrom == 'level3'">
                <div class="create_group-label"><?php echo $this->translate("Invite People to Your Group",'default'); ?> (<?php echo $this->translate("Optional",'default'); ?>)</div>
                <div style="position:relative">
					<div class="invited_friends">
						<div class="invited_names comn_profile_img" ng-repeat="item in objSelectedUsers" ng-click="RemoveFromInvitedUsers(item.user_id)">
							<img alt="" ng-if="item.user_image!=null&&item.user_image!=''" src="<?php echo $this->basePath(); ?>/public/datagd/profile/{{item.user_id}}/{{ item.user_image }}">
							<img alt="" ng-if="(item.user_image==null||item.user_image=='')&&(item.user_fbid!=null&&item.user_fbid!='')" src="https://graph.facebook.com/{{item.user_fbid}}/picture?width=66&&height=66">
							<img alt="" ng-if="(item.user_image==null||item.user_image=='')&&(item.user_fbid==null||item.user_fbid=='')" src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg">{{item.user_name}}<span></span>
						</div>                  
					</div>
					<div class="invite_suggession_common">
						<div class="login-field">
							<input name="name"  id="invite_list_friend" type="text" ng-model="friend_search" placeholder="+ <?php echo $this->translate("Add more people",'default'); ?>" ng-focus="enablelist=1" ng-blur="enablelist=0"  />
						</div>
						<div class="listed_members_container"  id="listed_members_container" style="display:none" >
							<div id="listed_members_container_inner" ng-init="enableScrollbarInvite()" >
							<ul id="invite_list_friend_ul">
								<li ng-repeat="item in filteredfriends = (friends | filter:friend_search)" class="invite_user_container" remove-on-click ng-click="AddToInvitedUsers(item.user_id,item.user_given_name,item.profile_photo,item.user_fbid);remove();" id="myfriend{{$index}}">
									<div class="profile_imaage comn_profile_img">
										<img alt="" ng-if="item.profile_photo!=null&&item.profile_photo!=''" src="<?php echo $this->basePath(); ?>/public/datagd/profile/{{item.user_id}}/{{ item.profile_photo }}">
										<img alt="" ng-if="(item.profile_photo==null||item.profile_photo=='')&&(item.user_fbid!=null&&item.user_fbid!='')" src="https://graph.facebook.com/{{item.user_fbid}}/picture?width=66&&height=66">
										<img alt="" ng-if="(item.profile_photo==null||item.profile_photo=='')&&(item.user_fbid==null||item.user_fbid=='')" src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg">
									</div>
									<div class="invite_user_name">{{item.user_given_name}}</div>	
								</li>
							</ul>
							<input type="hidden" id="hid_filterFriends" value="{{filteredfriends.length}}" />
							</div>
							<div ng-if="filteredfriends.length==0" class="matching_profile_messages"><?php echo $this->translate("No matching profiles",'default'); ?></div>
						 </div>
					</div>
				 </div>
                
                <div class="create_group-label"><?php echo $this->translate("Add Questionary",'default'); ?> (<?php echo $this->translate("Optional",'default'); ?>)</div>
                <div class="create_group_info"><?php echo $this->translate("Once people start sending their requests to join your group, the questionnaire can be helpful. By asking few questions, you can learn about your potential group members and make better choices about who should be able to join your group",'default'); ?>.</div>

                 <div ng-repeat="a in range(qn) track by $index">
                    <div class="create_group-label"><?php echo $this->translate("Question",'default'); ?> {{$index+1}}</div>
					<div class="questionnaireedit-outer" >
						<a id="dLabel_{{$index}}" data-toggle="dropdown" class="" href="javascript:void(0);">{{questiondrpClass[$index].locale}}</a>
						<ul aria-labelledby="dLabel_{{$index}}" role="menu" class="dropdown-menu questions_dropdown">
							<li ng-repeat="item in QuestionType"><a href="javascript:void(0)" ng-click="selectType($parent.$index,item.type,item.locale)" >{{item.locale}}</a></li>
						</ul>					 
					</div>	
                    <div class="clear"></div>
					<div class="login-field">
						<textarea ng-model="question[$index]"  placeholder="<?php echo $this->translate("Type Your Question",'default'); ?>"></textarea>
					</div>
					<div ng-if="selectedIndexQue[$index] == $index && (selected_type[$index]=='CheckBox'||selected_type[$index]=='Radiobutton')">
						<div class="clear"></div>
						<div ng-if="$index==0">
							<div  ng-repeat="opt in optionrange(selectedOptionRange[0]) track by $index">
								<div class="group_select_col-left">
									<input name="" type="text" placeholder="<?php echo $this->translate("Type Your Options",'default'); ?>" ng-model="option1[$index]"   />
								</div>
								<div class="clear"></div>
							</div>
							<div class="add-outer-container">
							<a href="javascript:void(0)" ng-click="addmoreOptions($index)" ng-if="selectedOptionRange[0]<10" class="add_more_question"><?php echo $this->translate("add",'default'); ?><i></i></a>
							<a href="javascript:void(0)" ng-click="removeOptions($index)" ng-if="selectedOptionRange[0]>3" class="remove_more_question"><?php echo $this->translate("remove",'default'); ?><i></i></a>
							</div>
						</div>
						<div ng-if="$index==1">
							<div  ng-repeat="opt in optionrange(selectedOptionRange[1]) track by $index">
								<div class="group_select_col-left">
									<input name="" type="text" placeholder="<?php echo $this->translate("Type Your Options",'default'); ?>" ng-model="option2[$index]"   />
								</div>
								<div class="clear"></div>
							</div>
							<div class="add-outer-container">
							<a href="javascript:void(0)" ng-click="addmoreOptions($index)" ng-if="selectedOptionRange[1]<10" class="add_more_question"><?php echo $this->translate("add",'default'); ?><i></i></a>
							<a href="javascript:void(0)" ng-click="removeOptions($index)" ng-if="selectedOptionRange[1]>3" class="remove_more_question"><?php echo $this->translate("remove",'default'); ?><i></i></a>
							</div>
						</div>
						<div ng-if="$index==2">
							<div  ng-repeat="opt in optionrange(selectedOptionRange[2]) track by $index">
								<div class="group_select_col-left">
									<input name="" type="text" placeholder="<?php echo $this->translate("Type Your Options",'default'); ?>" ng-model="option3[$index]"   />
								</div>
								<div class="clear"></div>
							</div>
							<div class="add-outer-container">
							<a href="javascript:void(0)" ng-click="addmoreOptions($index)" ng-if="selectedOptionRange[2]<10" class="add_more_question"><?php echo $this->translate("add",'default'); ?><i></i></a>
							<a href="javascript:void(0)" ng-click="removeOptions($index)" ng-if="selectedOptionRange[2]>3" class="remove_more_question"><?php echo $this->translate("remove",'default'); ?><i></i></a>
							</div>
						</div>
					</div>
                    <div class="clear"></div>
                </div>

                <div class="login-field" ng-if="addmoreQuestion==1">
                	<span class="group_questionary create_group_questionary">
                       <a href="javascript:void(0);" ng-click="qn=3;hideContainer()" ><i></i><?php echo $this->translate("Click to add question",'default'); ?> (<?php echo $this->translate("1 questions left",'default'); ?>)</a>
                    </span>
                </div>
				 <div id="question_error" style="color:#ff0000"></div>
               	<div class="signup_button" ng-if="createGroupAjax==1">
                     <img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif" />
                </div>
                <div class="signup_button" ng-if="createGroupAjax==0">
                    <div class="signup-link"><a href="javascript:void(0);" class="default_butn_normal" id="" ng-click="goback('level2')"><?php echo $this->translate("Back",'default'); ?></a> <a href="javascript:void(0);" class="default_butn_blue" id="" ng-click="SaveGroup()"><?php echo $this->translate("Finish",'default'); ?></a></div>
                    <div class="clear"></div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
	<div class="pop_bg modal fade" id="confirm_popup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog login_popup">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo $this->translate("Close",'default'); ?></span></button>
            <div class="clear"></div>
          </div>
          <div class="modal-body signup_body">
			<div id="signup_step1">
				<div class="step1_outer">
					<h3><?php echo $this->translate("Please Confirm",'default'); ?></h3>
					 <div class="already_member"> <?php echo $this->translate("You are about to leave the group",'default'); ?> <span>{{selectedGroupRemoved}}</span>.<?php echo $this->translate("Are you sure?",'default'); ?> 
						<div class="leave_group_btn">
						<a href="javascript:void(0);" class="default_butn_blue" ng-click="leaveGroup()"><?php echo $this->translate("Yes I'm sure",'default'); ?> </a>
						<a href="javascript:void(0);" class="default_butn_red" id="cancel_reply" ng-click="showReply=0;removeLeaveBox()" data-dismiss="modal"><?php echo $this->translate("No",'default'); ?></a>
						</div>
					</div>
				</div>
			</div>
          </div>
          
        </div>
      </div>
    </div>
	<div class="pop_bg modal fade" id="join_group" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog join_group_popup">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo $this->translate("Close",'default'); ?></span></button>
            <div class="clear"></div>
          </div>
          <div class="modal-body signup_body">
            <div class="step1_join" id="step_1" ng-if="(profile.user_profile_about_me==''||profile.user_profile_about_me==null||profile.user_profile_about_me=='null')&&joingroupStep==1">
                <h3><?php echo $this->translate("Introduce Yourself",'default'); ?></h3>
                <div class="already_member signup_po-link"><?php echo $this->translate("Looks like you haven’t written your bio, why don’t you introduce yourself to the group? *You can edit this later on your profile page",'default'); ?><br />&nbsp;</div>
                <div class="login-field introduce_textarea">
                    <textarea name="Introduction" placeholder="<?php echo $this->translate("Tell something interesting about yourself",'default'); ?>" ng-model="aboutme"></textarea>
                </div>
                
                <div class="login_button">
                   <!-- <a href="javascript:void(0);" class="default_butn_normal" ng-click="aboutme='';closeJoinWindow();">Cancel</a> -->
				   <a href="javascript:void(0);" class="default_butn_grey" ng-click="aboutme='';skipJoinRequest(1)"><?php echo $this->translate("Skip",'default'); ?></a>
					<div ng-if="aboutmeAjax==1" class="loading"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> </div>
                    <a ng-if="aboutmeAjax==0" href="javascript:void(0);" class="default_butn_blue" id="step_2_join" ng-click="SaveAboutMe(aboutme)"><?php echo $this->translate("Continue",'default'); ?></a>
                </div>
            </div>
            <div class="step1_join" id="step_2" ng-if="joingroupStep==2">
            	<h3><?php echo $this->translate("Upload Your Photo",'default'); ?></h3>
                <div class="upload_photo-outer">
                	<div class="browse_photo profile_img-edit">
                    	<a href="javascript:void(0);"  data-toggle="modal" data-target="#join_upload_profile-image" ng-click="loadProfileUpload()"  id="loadProfileUpload">
                            <span>
                                <i class="change_cover"></i><br>
                               <?php echo $this->translate("Upload",'default'); ?>
                            </span>
                        </a>
                    </div>
                   <div class="photo_details"><?php echo $this->translate("Looks like you haven’t uploaded your profile photo. You can do it now (this improves your credibility on Jeera).",'default'); ?> <br />*<?php echo $this->translate("You can change this later on your profile page",'default'); ?>.</div>
                    <div class="clear"></div>
                </div>
                <div class="login_button">  
					<a href="javascript:void(0);" class="default_butn_grey" ng-click="skipJoinRequest(2)"><?php echo $this->translate("Skip",'default'); ?></a>
                    <a href="javascript:void(0);" class="default_butn_blue" id="step_3_join" ng-click="gotoGroupJoiningStep3()"><?php echo $this->translate("Continue",'default'); ?></a>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="step1_join" id="step_3"  ng-if="joingroupStep==3">
				<h2 class="question_title"><?php echo $this->translate("How about knowing a bit more about you?",'default'); ?></h2>
				<span ng-repeat="items in  joingingquestionnaire">
			   <h3>{{items.question}}</h3>
                <div class="login-field introduce_textarea" ng-if="items.answer_type == 'Textarea'">
                    <textarea name="answer" placeholder="<?php echo $this->translate("Your Answer",'default'); ?>" ng-model="md_questionnaire[$index]"></textarea>
                </div>				                 
                <div class="login-field introduce_textarea" ng-if="items.answer_type == 'radio'">
                    <div class="select_group-type join_radio" ng-repeat="option in items.options">
                    	<input type="radio" value="{{option.option_id}}"  name="group_type_{{items.questionnaire_id}}" id="Public-group-{{$parent.$index}}{{$index}}" ng-click="selectedOptionRadio(items.questionnaire_id,option.option_id)">
                        <label for="Public-group-{{$parent.$index}}{{$index}}"><i class="radio-styled"></i> {{option.option}}</label>
                        <div class="clear"></div>
                    </div>
                     
                </div>
				
				<div class="login-field introduce_textarea" ng-if="items.answer_type == 'checkbox'">
					<div class="checkbox_outer">
						<ul class="notify_list">
							<li ng-repeat="option in items.options"><a href="javascript:void(0)" ng-click="selectedOptionCheckbox(items.questionnaire_id,option.option_id,$parent.$index)">
							<i class="check_blue" ng-if="!checkInList(items.questionnaire_id,option.option_id,$parent.$index)"></i>
							<i class="check_blue_checked" ng-if="checkInList(items.questionnaire_id,option.option_id,$parent.$index)"></i>
							{{option.option}}</a></li>
						</ul>                        
                    </div>                    
                </div>				
			</span>				
                <div class="login_button">
					<a href="javascript:void(0);" class="default_butn_grey" ng-click="skipJoinRequest(3)"><?php echo $this->translate("Skip",'default'); ?></a>
					<div ng-if="aboutmeAjax==1" class="loading"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> </div>
					
                    <a href="javascript:void(0);" ng-if="aboutmeAjax!=1" class="default_butn_blue" id="step_4_join" ng-click="saveQuestionnaireAnswers()"><?php echo $this->translate("Continue",'default'); ?></a>
                    <div class="clear"></div>
                </div>
            </div>
            
            <div class="step1_join" id="step_4"  ng-if="joingroupStep==4">
				<h3 ng-if="JoiningItemType == 'public'||JoiningItemType == 'private'"><?php echo $this->translate("Your request has been sent",'default'); ?>.</h3>
				<h3 ng-if="JoiningItemType == 'open'"><?php echo $this->translate("Thank you for joining this group",'default'); ?>.</h3>
                
                
                <div class="login_button">
                    <a href="<?php echo $this->basePath(); ?>/explore?similar={{JoiningItem}}" class="default_butn_yellow"><?php echo $this->translate("Show Me Some More Similar Groups",'default'); ?></a>
                    <a href="<?php echo $this->basePath(); ?>/groups/{{JoiningItemseoTitile}}" class="default_butn_blue" id="" ><?php echo $this->translate("Continue",'default'); ?></a>
                </div>
            </div>
            
            
         </div>
          
        </div>
      </div>
    </div>
	<div class="pop_bg modal fade" id="join_upload_profile-image" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog upload-img_popup">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo $this->translate("Close",'default'); ?></span></button>
            <div class="clear"></div>
          </div>
          <div class="modal-body signup_body">
                <div class="step1_outer">
                    <h3><?php echo $this->translate("Position and Size Your Photo",'default'); ?></h3>
                    <div class="profile-pic_preview_outer">
                    	<div class="image-editor-group">
                              <div class="browse-profile_image"><input type="file" class="cropit-image-input" id="profile_image_file"></div>
                              <!-- .cropit-image-preview-container is needed for background image to work -->
                              <div class="cropit-image-preview-container">
                                <div class="cropit-image-preview"></div>
                              </div>
                              <div class="image_zoom-bar">
                              	<input type="range" class="cropit-image-zoom-input">
                              </div>
							  <div id="profilepic_process">
							  </div>
                              <div class="upload-img_butns">
                              	<a href="javascript:void(0);" class="default_butn_red" ng-click="cancelImageUpload()"><?php echo $this->translate("Cancel",'default'); ?></a>
								<div ng-if="aboutmeAjax==1" class="loading"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"> </div>
                                <a href="javascript:void(0);"  ng-if="aboutmeAjax==0" class="default_butn_blue" ng-click="cropImage()"><?php echo $this->translate("Apply",'default'); ?></a>
                              </div>
                              
                        </div>
                    </div>
                    
                </div>
            
          </div>
          
        </div>
      </div>
    </div>
	<div class="pop_bg modal fade" id="friends_popup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog login_popup">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"><?php echo $this->translate("Close",'default'); ?></span></button>
            <div class="clear"></div>
          </div>
          <div class="modal-body signup_body"  id="friends_list_outer" ng-init="enableScrollbarFriendsPopup()" >
				<div ng-if="loadpeople==1"><img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif"></div>
          		<div class="likes_pop-outer" ng-if="loadpeople==0" id="friends_list_outer" >
                	<div class="like_profile-outer" ng-repeat="items in friendsList">
                    	<div class="like_profile-img comn_profile_img">
							<img alt="" ng-if="items.profile_photo!=null&&items.profile_photo!=''" src="<?php echo $this->basePath(); ?>/public/datagd/profile/{{items.user_id}}/{{ items.profile_photo }}">
							<img alt="" ng-if="(items.profile_photo==null||items.profile_photo=='')&&(items.user_fbid!=null&&items.user_fbid!='')" src="https://graph.facebook.com/{{items.user_fbid}}/picture?width=66&&height=66">
							<img alt="" ng-if="(items.profile_photo==null||items.profile_photo=='')&&(items.user_fbid==null||items.user_fbid=='')" src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg">
						 
						</div>
                        <div class="like_profile-name"><a href="javascript:void(0);">{{items.user_given_name}}</a></div>
                         		 
                    </div>
					<div><a href="javascript:void(0)" ng-if="friendsList.length<groupFriends_count" ng-click="LoadFriendsUsers(popup_group_id,popup_group_page+1,groupFriends_count)"><?php echo $this->translate("Loadmore",'default'); ?></span></a></div>
                </div>
          </div>
          
        </div>
      </div>
    </div>
    </div>
<div id="group_dialog" title="" style="display:none" class="common_error"></div>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/public/js/jquery.cropit.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/public/js/jquery.slimscroll.js"></script>
<script>
    var arrInviteFriends    = new Array();
    var profileImgpath      = baseurl+'/public/datagd/profile/';
	var page = 1;
    $.widget("custom.catcomplete", $.ui.autocomplete, {
		_renderMenu: function (ul, items) {
			var that = this;
			$.each(items, function (index, item) {
				// that._renderItemData(ul, item);
				var fnc     = 'selectMatch('+item.userid+','+item.fid+',"'+item.label+'","'+item.profilePhoto+'")';
				if(item.profilePhoto==''||item.profilePhoto=='null'||item.profilePhoto==null){
					$( "<li>" )
					.append( $( '<a onclick='+fnc+'>').text( item.label ).prepend('<img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" />') )
					.appendTo( ul ).data( "ui-autocomplete-item", item );
				}else{
					$( "<li>" )
					.append( $( '<a onclick='+fnc+'>').text( item.label ).prepend('<img src="'+profileImgpath+item.userid+'/'+item.profilePhoto+'" />') )
					.appendTo( ul ).data( "ui-autocomplete-item", item );
				}
			});
		}
    });
     // fucntion to remoce friends
	function removeAddedFriends(fid){
		for(var i=0; i<arrInviteFriends.length; i++){
			if(arrInviteFriends[i].fid == fid){
				  arrInviteFriends.splice(i,1);
			 }
		}// for
		displayAddedFriends(arrInviteFriends);          // display
	}
    // fucntion to display added friends
    function selectMatch(uid ,fid, name, p_photo){
        var errorFlag   = 0;
        for(var i=0; i<arrInviteFriends.length; i++){ // check duplicate id
			if(arrInviteFriends[i].fid == fid){
			  errorFlag   = 1;
			  break;
			}
        }// for
        if(errorFlag == 1){
            $("#group_dialog").html('<?php echo $this->translate("This friend is already added",'default'); ?>.');
			$("#group_dialog").dialog();
        }else{
             arrInviteFriends.push({ userid:uid, fid: fid, fname: name, profilePhoto: p_photo}); // add into the array
             displayAddedFriends(arrInviteFriends);          // display
        }// else
    }// function
    // function to display added friends list
    function displayAddedFriends(arrInviteFriends){
        $('#addInviteFriend').empty();                   // make div empty
        for(var i=0; i<arrInviteFriends.length; i++){    // display added friends
            var remFnc     = 'removeAddedFriends('+arrInviteFriends[i].fid+')'; // fucntion to remove friends
			if(arrInviteFriends[i].profilePhoto == ''||arrInviteFriends[i].profilePhoto == null||arrInviteFriends[i].profilePhoto == 'null'){
				$('#addInviteFriend').append('<div class="invited_names comn_profile_img"><img src="<?php echo $this->basePath(); ?>/public/images/noimg.jpg" alt="" />'+arrInviteFriends[i].fname+'<span onclick='+remFnc+'></span></div>&nbsp');
			}else{
				$('#addInviteFriend').append('<div class="invited_names comn_profile_img"><img src="'+profileImgpath+arrInviteFriends[i].profilePhoto+'" alt="" />'+arrInviteFriends[i].fname+'<span onclick='+remFnc+'></span></div>&nbsp');
			}
        }// for
    }// function
	var image_paths = <?php echo json_encode($image_folders); ?>;
	var uploadFIle = '';
    var groupapp = angular.module('groupapp',[]);
	groupapp.config(function ($httpProvider) {
		$httpProvider.defaults.transformRequest = function(data){
			if (data === undefined) {
				return data;
			}
			return $.param(data);
		}
	});
	groupapp.directive('autoComplete', function ($timeout) {
		return function (scope, iElement, iAttrs) {
			iElement.autocomplete({
				source: scope[iAttrs.uiItems],
				select: function () {
					$timeout(function () {
						iElement.trigger('input');
					}, 0);
				}
			});
		};
	});
	groupapp.directive('scroller', function ($window) {
		return {
			restrict: 'A',
			link: function(scope, element, attrs) {
			  var windowEl = angular.element($window); 		  
			  var handler = function() { scope.handler();  }
			  windowEl.on('scroll', scope.$apply.bind(scope, handler));
			 
			}
		};
	});
    groupapp.controller('groupController',function($scope, $http){
		$scope.Searchcompany = [];
		$scope.CompanyContactAutocompleteBind = function () {
			$("#usersearch").catcomplete({
				delay: 0,
				source: $scope.Searchcompany
			});
		};
		$scope.profile ={};
		$scope.USERprofile = <?php echo json_encode($profile_data); ?>;
		$scope.frineds_count = <?php echo $friends_count; ?>;
		$scope.group_count = <?php echo $group_count; ?>;
		$scope.created_group_count = <?php echo $created_group_count; ?>;
		$scope.joined_group_count = <?php echo $joined_group_count; ?>;
		$scope.pending_group_count = <?php echo $pending_group_count; ?>;
		$scope.mutual_group_count = <?php echo $mutual_count; ?>;
		$scope.profile.profile_photo = '<?php echo $profile_data->profile_photo; ?>';
		$scope.profile.user_id = '<?php echo $profile_data->user_id; ?>';
		$scope.profile.user_fbid = '<?php echo $profile_data->user_fbid; ?>';
		$scope.myprofile = '<?php echo $myprofile; ?>';
		$scope.myIntrest = <?php echo json_encode($myIntrests); ?>;
		$scope.profile.user_profile_about_me = $scope.USERprofile.user_profile_about_me;
		$scope.user = {};
		$scope.item = {};
		$scope.categoryImagePath=(image_paths.tag_category!='')?baseurl+"/public/"+image_paths.tag_category:baseurl+'/public/images/';
		$scope.groupImagePath =  (image_paths.group!='')?baseurl+"/public/"+image_paths.group:baseurl+'/public/images/';
		$scope.loading=false;
		$scope.profileData = {};
		$scope.country = '';
		$scope.user.country = '';
		$scope.city = '';
		$scope.profileData.switch  =  1;
		$scope.user.cityId   = '';
		$scope.user.grouptype = 1;
		$scope.master = {};
		$scope.addedtags = [];
		$scope.intrest = {};
		$scope.intrest.switch = 2;
		$scope.drpClass = "dropdown_close";
		$scope.isVisible = 0;
		$scope.selectedIndex = 0;
		$scope.tag_search='';
		$scope.TextType  = '';
		$scope.objSelectedCategory =  new Array();
		$scope.addmoreQuestion = 1;
		$scope.sendtosave = 0;
		$scope.selectedIndex = [];
		$scope.selectedOptionRange=[3,3,3];
		$scope.name = [];
		$scope.question = [];
		$scope.question_type = [];
		$scope.selected_type= [];
		$scope.option1 = [];
		$scope.option2 = [];
		$scope.option3 = [];
		$scope.QuestionDetails = [];
		$scope.qn = 2;
		$scope.selectedIndexQue = [];
		$scope.friendsName = [];
		$scope.addedFriendsName = [];
		$scope.selectedFrom = 'level1';
		$scope.mygroup= {};
		$scope.mygroup.groupTitle='';
		$scope.mygroup.country='';
		$scope.mygroup.city='';
		$scope.mygroup.description='';
		$scope.Locationloading = true;
		$scope.groupCategory = [];
		$scope.groupintrest = {};
		$scope.groupintrest.switch = 2; 
		$scope.grouptags = {};
		$scope.showgrouptags = 0;
		$scope.showgroupmoretags = 0;
		$scope.group_tag_limit = 25;
		$scope.group_tag_inc_limit = 25;
		$scope.gruopdrpClass = "dropdown_close";
		$scope.gruopisVisible = 0;			 
		$scope.groupselectedIndex = 0;	
		$scope.selectedGroupCategory = '';
		$scope.isCountryDropVisible =0;
		$scope.countrydrpClass = "dropdown_close";
		$scope.isCityDropVisible =0;
		$scope.citydrpClass = "dropdown_close";
		$scope.isCityDropVisible = 0;
		$scope.isCityDefault = 0;
		$scope.citydrpClass = "dropdown_close";
		$scope.city_selected = '';
		$scope.selectedGroupIntrestCategory = '';
		$scope.selectedGroupIntrestCategoryIcon = '';
		$scope.QuestionType = [];
		$scope.checkCommonIntrests = function(tag_id){
			var is_exist = -1;
			for(i=0;i<$scope.myIntrest.length;i++){
				if($scope.myIntrest[i].tag_id == tag_id){	
					is_exist =i;
				}
			}
			if(is_exist!=-1){return true;}else{return false;}
		}
		$scope.loadFirstFrom = function(){	
			$scope.selectedFrom = 'level1';
			url  = baseurl+'/country/ajaxCountryList';				 
			$http({
			  method: 'POST',
			  url: url
			}).success(function(data, status, headers, config) {                    
				$scope.country   = data.countries;				   
				$scope.Locationloading = false;
				$scope.CitySelect(data.countries[0].country_id);
				$scope.mygroup.country = data.countries[0].country_id;	
				$scope.country_title =  data.countries[0].country_title_locale;
			}).error(function(data, status, headers, config) {
				// alert("Error occured. Please try again");
				 $scope.Locationloading = false;
			});
		}
		$scope.CitySelect = function(country_value){
			$scope.Locationloading=true;
			url  = baseurl+'/city/ajaxCitiesList';
			$http.post(url,{country_id:country_value}, {headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}
			).success(function(data, status, headers, config) {				     
				$scope.Locationloading=false;
				$scope.city  = data.cities; 
				$scope.mygroup.city = data.cities[0].city_id;
				$scope.city_selected = data.cities[0].city_locale;
			}).error(function(data, status, headers, config) {
				$scope.Locationloading=false;
				// alert("Error occured. Please try again");
			});
		};
		$scope.clearForms = function(){
			$scope.mygroup= {};
			uploadFIle = '';
			$("#create_group").modal("hide");
		}
		
		$scope.LoadSecondFrom = function(){  
			var error_count = 0;
			if($scope.mygroup.groupTitle==''){  
				$scope.groupTitileError = 1;
				error_count++;
			}
			if($scope.mygroup.country==''){  
				$scope.groupCountryError = 1;
				error_count++;
			}
			if($scope.mygroup.city==''){	 
				$scope.groupCountryError = 1;
				error_count++;
			}
			if($scope.mygroup.description==''){   
				$scope.groupDescriptionError = 1;
				error_count++;
			}
			if(error_count==0){  
				$scope.selectedFrom = 'level2';
				$scope.groupintrest.switch = 2; 
				url = baseurl+'/tag/getAllActiveCategories';
				$http({
				  method: 'POST',
				  url: url
				}).success(function(data, status, headers, config) {
				   $scope.groupCategory=data.tag_category;	
				  $scope.getgroupTags(data.tag_category[0].tag_category_id);		
					//$scope.selectedGroupCategory ='All';
					//$scope.getgroupTags('All');	
					$scope.selectedGroupIntrestCategory = data.tag_category[0].tag_category_title_locale;
					$scope.selectedGroupIntrestCategoryIcon = data.tag_category[0].tag_category_icon;
				   $scope.groupintrest.switch = 1; 
				}).error(function(data, status, headers, config) {
					// alert("Error occured. Please try again");
				});
			}
		}			
		$scope.enableGroupIntrestScrollBar = function(){
			$('#group_intrest_category_list').slimScroll({
			  color: '#00f',height:'250px'
			});				 
		}
		$scope.selectGroupIntrestCategory = function(category,icon,title){  
			$scope.selectedGroupIntrestCategory = title;
			$scope.selectedGroupIntrestCategoryIcon = icon; 
			$scope.selectedGroupCategory = category;
			$scope.group_tag_limit = 25;
			$scope.showgroupmoretags = 0;
			$scope.showgrouptags = 0;	
			$scope.getgroupTags(category);	
		};	
		$scope.getgroupTags = function(category){
			$scope.showgrouptags = 0;
			url  = baseurl+'/tag/getAllTagsOfSelectedCategory';				
			$http.post(url,{category_id:category,search:$scope.grouptag_search}, {headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) { 
				if(data.tags.length>0){
				$scope.grouptags = data.tags; 	
				$scope.showgrouptags = 1;
				$scope.group_tag_limit = 25; 
				}else{$scope.showgrouptags = 0;}
				if(data.tags.length > $scope.group_tag_limit){
				$scope.showgroupmoretags = 1;
				}else{$scope.showgroupmoretags = 0;}
			}).error(function(data, status, headers, config) {
			 //alert("Error occured. Please try again");
			});
		};
		$scope.increaseLimit = function (group_tag_limit){
			$scope.group_tag_limit = group_tag_limit+$scope.group_tag_inc_limit;  
		};
		$scope.objSelectedGroupTags = new Array();
		$scope.objSelectedGroupCategory = new Array()
		$scope.addToSelectedGroupIntrest = function(category,tag_id,tag_name){  
			var incexist = 0;
			angular.forEach($scope.objSelectedGroupTags, function(dataset){ 
				if(dataset.tag_name == tag_name){incexist++;}
			});				
			if(incexist == 0){
				$scope.objSelectedGroupTags.push({
					category:category,tag_id:tag_id,tag_name:tag_name
				});
			}
			angular.forEach($scope.groupCategory, function(dataset){ 
				if(dataset.tag_category_id == category){
					var incexist = 0;
					angular.forEach($scope.objSelectedGroupCategory, function(datasets){ 
						if(datasets.category_icon == dataset.tag_category_icon){incexist++;}						 
					});	
					if(incexist ==0){
						$scope.objSelectedGroupCategory.push({
							category:dataset.tag_category_id,category_title:dataset.tag_category_title,category_icon:dataset.tag_category_icon
						});	
					}
				}
			});			 
		};
		$scope.removeFromSelectedGroupIntrest = function(tag_name,category){ 			 
			var array_index = $scope.getArrayIndex($scope.objSelectedGroupTags,'tag_name',tag_name);
			$scope.objSelectedGroupTags.splice( array_index, 1 );
			var incexist = 0;
			angular.forEach($scope.objSelectedGroupTags, function(dataset){ 
				if(dataset.category == category){incexist++;}
			});				
			if(incexist == 0){
				var array_index = $scope.getArrayIndex($scope.objSelectedGroupCategory,'category',category);
				$scope.objSelectedGroupCategory.splice( array_index, 1 );
			}
		};
		$scope.savethis = function(){
			angular.forEach($scope.name, function(dataset){
				alert(dataset)
			});
		}
		$scope.range = function(n) {
			return new Array(n);
		}
		$scope.hideContainer=function(){
			$scope.addmoreQuestion = 0;
			$scope.qn = 3;
		}
		$scope.selectType = function(id,item,locale){
			$scope.selectedIndexQue[id] = id;
			$scope.question_type[id] = item;
			$scope.selected_type[id]= $scope.question_type[id];				
			$scope.questiondrpClass[id].selected = item;
			$scope.questiondrpClass[id].locale = locale;
			if($scope.question_type[id] == 'Select Question Type'){
				$scope.question[id]     = '';
				$scope.option1[id]      = '';
				$scope.option2[id]      = '';
				$scope.option3[id]      = '';
			}
		}
		$scope.questiondrpClass = [];
		$scope.questiondrpClass[0] = {selected:"Select Question Type",locale:"<?php echo $this->translate('Select Question Type','default'); ?>"};
		$scope.questiondrpClass[1] = {selected:"Select Question Type",locale:"<?php echo $this->translate('Select Question Type','default'); ?>"};
		$scope.questiondrpClass[2] = {selected:"Select Question Type",locale:"<?php echo $this->translate('Select Question Type','default'); ?>"};
		$scope.selectedQuestionnaireType = function(row,item){ 
			$scope.questiondrpClass[row].selected = item;
			$scope.selectedType[row] =  item;
		}
		// saving the group
		$scope.createGroupAjax = 0;
        $scope.SaveGroup = function(){
			$scope.QuestionDetails = [];
			var index = 0;
			var flag  = 0;
			angular.forEach($scope.question_type, function(dataset){  
					if((dataset != undefined)&&(dataset != 'Select Question Type')){  
						if($scope.question[index]==undefined||$scope.question[index]==''){  
							$("#question_error").html('<?php echo $this->translate("Please enter question",'default'); ?> '+(Number(index) + Number(1))); 
							flag = 1; 
							return false;
						}
						var options = [];
						if(dataset!='Textarea'){ 
							if(index==0){  
								var options = $scope.option1.filter(function(n){ return n != undefined }); 
								if(options.length<2){
									$("#question_error").html('<?php echo $this->translate("Please enter atleast two options for question",'default'); ?> '+(Number(index) + Number(1)));
									flag = 1;
									return false;
								}
							}
							if(index==1){  
								var options = $scope.option2.filter(function(n){ return n != undefined });
								if(options.length<2){
									$("#question_error").html('<?php echo $this->translate("Please enter atleast two options for question",'default'); ?> '+(Number(index) + Number(1)));
									flag = 1;
									return false;
								}
							}
							if(index==2){
								var options = $scope.option3.filter(function(n){ return n != undefined }); 
								if(options.length<2){
									$("#question_error").html('<?php echo $this->translate("Please enter atleast two options for question",'default'); ?> '+(Number(index) + Number(1)));
									flag = 1;
									return false;
								}
							}
							$scope.QuestionDetails.push({
									QuestionType    :dataset,
									QuestionDecp    :$scope.question[index],
									options :options
							});
						}else{
							$scope.QuestionDetails.push({
									QuestionType    :dataset,
									QuestionDecp    :$scope.question[index],
									options :''
							});
						}
					}
                 index++;
				});
			if(flag == 0){
				$scope.sendtosave = 1;
				var formData    = new FormData();
				var addedTags   = [];
				var increment   = 0;
				var addedQue    = [];
				var addedFriends = [];
			   // $scope.addedFriendsName = arrInviteFriends;
				angular.forEach($scope.objSelectedGroupTags, function(dataset){
					addedTags[increment] = dataset.tag_id;
					increment++;
				});
				// concate the questions
				increment   = 0;
				angular.forEach($scope.QuestionDetails, function(dataset){
					str_questionnaire = '';
					str_questionnaire += dataset.QuestionType+'##'+dataset.QuestionDecp;
					angular.forEach(dataset.options, function(optionset){
						 str_questionnaire +='##'+optionset;
					});
					addedQue[increment] = str_questionnaire;
					increment++;
					
				});
				// concate friends
				increment   = 0;
				angular.forEach($scope.objSelectedUsers, function(dataset){
					addedFriends[increment] = dataset.user_id;
					increment++;
				});
				$scope.createGroupAjax = 1;
				formData.append("groupImage",uploadFIle);
				formData.append("strGroupName", $scope.mygroup.groupTitle);
				formData.append("intCountryId", $scope.mygroup.country);
				formData.append("intCityId", $scope.mygroup.city);
				formData.append("strDesp", $scope.mygroup.description);
				formData.append("intGroupType", $scope.mygroup.grouptype);
				formData.append("addedtags",addedTags);
				formData.append("addedFriends",addedFriends);
				formData.append("QuestionDetails",addedQue);
				$("#question_error").html("");
				url = baseurl + '/groups/creategroup';
                $http.post(url,formData,{withCredentials: true, headers: {'Content-Type': undefined }, transformRequest: angular.identity})
                .success(function(data, status, headers, config) {
					if(data.return_array.process_status == 'success'){
					   // alert('success');
						if(data.return_array.seotitle!=''){
							window.location.href='<?php echo $this->basePath(); ?>/groups/'+data.return_array.seotitle;
						}else{
							window.location.reload();
						}
					}else{
						$scope.createGroupAjax = 0; 
						$("#group_dialog").html(data.return_array.process_info);
						$("#question_error").html(data.return_array.process_info);
						$("#group_dialog").dialog();
						$scope.sendtosave = 0;
					}
	 			})
				.error(function(data, status, headers, config) {
					$scope.createGroupAjax = 0;
					$("#group_dialog").html("<?php echo $this->translate("Error occurred. Please try again",'default'); ?>");
					$("#question_error").html("<?php echo $this->translate("Error occurred. Please try again",'default'); ?>");
					$("#group_dialog").dialog();
				});
			}			 
		}  
		$scope.goback = function(level){	
			$scope.selectedFrom = level;
		}
		$scope.friends = [];			
		$scope.objSelectedUsers = [];
		$scope.LoadThirdFrom = function(){
			if($scope.objSelectedGroupTags.length>0){
				$scope.selectedFrom = 'level3';
				url  = baseurl+'/groups/getuserfriends';
				$http({
					method: 'POST',
					url: url
				}).success(function(data, status, headers, config) {
				    $scope.friends   = data.friendsList;				    
				}).error(function(data, status, headers, config) {
					// alert("Error occured. Please try again");
				});
				$scope.QuestionType.push({
						type:"Select Question Type",locale:"<?php echo $this->translate('Select Question Type','default'); ?>"
					});
					$scope.QuestionType.push({
						type:"Textarea",locale:"<?php echo $this->translate('Textarea','default'); ?>"
					});
					$scope.QuestionType.push({
						type:"CheckBox",locale:"<?php echo $this->translate('CheckBox','default'); ?>"
					});
					$scope.QuestionType.push({
						type:"Radiobutton",locale:"<?php echo $this->translate('Radiobutton','default'); ?>"
					});
					 
					$scope.TextType            = '<?php echo $this->translate('Select Question Type','default'); ?>';
			}else{
				$scope.selectedFrom = 'level2';
				$scope.groupIntresetError = 1;
			}
		}
		$scope.AddToInvitedUsers = function(user_id,user_name,user_image,user_fbid){ 
			var incexist = 0;
			angular.forEach($scope.objSelectedUsers, function(dataset){ 
				if(dataset.user_id == user_id){incexist++;}
			});				
			if(incexist == 0){
				$scope.objSelectedUsers.push({
					user_id:user_id,user_name:user_name,user_image:user_image,user_fbid:user_fbid
				});
			}				
		}
		$scope.RemoveFromInvitedUsers = function(user_id){
			var array_index = $scope.getArrayIndex($scope.objSelectedUsers,'user_id',user_id);
			$scope.objSelectedUsers.splice( array_index, 1 );			 
		}
		$scope.hideList = function(){  
			if(!$scope.onlist)$scope.enablelist = 0;			 
		}
		$scope.OnListHover = function() { 
			$scope.onlist = 1;
			$scope.enablelist = 1;
		}
		$scope.OnListOut =  function(){ 
			$scope.onlist = 0;
			$scope.enablelist = 0;
		}
		$scope.getCityId = function(cityId){
			$scope.user.cityId = cityId;
		}
		$scope.removeData = function(){
			$scope.user = angular.copy($scope.master);
			$scope.user.grouptype = 1;
			uploadFIle = '';
			$('#uploadPreview').html('');
			$scope.objSelectedTags  = [];
			var index = 0;
			angular.forEach($scope.question_type, function(dataset){
					$scope.question[index]  = ''
					$scope.option1[index]   = '';
					$scope.option2[index]   = '';
					$scope.option3[index]   = '';
			index++;
			});
		}
		$scope.selectedType = 'All';
		$scope.page = 1;
		$scope.group_list =[];
		$scope.ajaxFlag = 0;
		$scope.selectedGroupRemoved = '';
		$scope.selectedGroupIdRemoved = '';			
		$scope.showGroups = function(page_scroller){				
			if($scope.ajaxFlag == 0){
				if(page_scroller){page++;}else{page=1;}
				$scope.page = page;
				$scope.ajaxFlag = 1;
				url = baseurl + '/groups/grouplist';
				$http.post(url,
				{
					profilename:'<?php echo $current_Profile;?>',
					page:page,					 
					type:$scope.selectedType,
				},{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}
				).success(function(data, status, headers, config) {
					if($scope.page>1){
						if(data.return_array.groups.length>0)
						$scope.group_list = $scope.group_list.concat(data.return_array.groups);						
					}else{ $scope.group_list = data.return_array.groups;}  
					$scope.ajaxFlag = 0;
				}).error(function(data, status, headers, config) {
					// alert("Error occured. Please try again");
					 $scope.ajaxFlag = 0;
				});
			}
		}
		$scope.handler = function() {		 
			$scope.showGroups(true);
		}
		$scope.showAll= function(){
			$scope.selectedType = 'All';
			$scope.showGroups(false);
		}
		$scope.showCreated= function(){
			$scope.selectedType = 'created';
			$scope.showGroups(false);
		}
		$scope.showJoined= function(){
			$scope.selectedType = 'joined';
			$scope.showGroups(false);
		}
		$scope.showPending= function(){
			$scope.selectedType = 'pending';
			$scope.showGroups(false);
		}
		$scope.showMutual= function(){
			$scope.selectedType = 'mutual';
			$scope.showGroups(false);
		}
		$scope.selectLeavingGroup = function(item_id,item_title){
			$scope.selectedGroupRemoved = item_title;
			$scope.selectedGroupIdRemoved = item_id;
		}
		$scope.removeLeaveBox= function(){
			$scope.selectedGroupRemoved = '';
			$scope.selectedGroupIdRemoved = '';
		}
		$scope.leaveGroup = function(){
			url = baseurl + '/groups/leavegroup';
			$http.post(url,{groupId:$scope.selectedGroupIdRemoved},{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}
			).success(function(data, status, headers, config) {
				if(data.return_array.process_status == 'success'){
					$('#confirm_popup').modal('hide');						
					var array_index = $scope.getArrayIndex($scope.group_list,'group_id',$scope.selectedGroupIdRemoved); 
					$scope.group_list.splice( array_index, 1 );
					$scope.selectedGroupRemoved = '';
					$scope.selectedGroupIdRemoved = '';		
					$scope.group_count=$scope.group_count*1-1;			
					$scope.joined_group_count=$scope.joined_group_count*1-1;						
				}else{
					$("#group_dialog").html(data.return_array.process_info);
					$("#group_dialog").dialog();
				}
			}).error(function(data, status, headers, config) {
				// alert("Error occured. Please try again");
			});
		}
		$scope.getArrayIndex = function(arr_elemnt,key,item){ 
			var incexist = -1;
			for(i=0;i<arr_elemnt.length;i++) {
				if(arr_elemnt[i][key] == item){incexist = i;}
			}
			return incexist;
		};
		if($scope.profile.user_profile_about_me!=''&&$scope.profile.user_profile_about_me!=null&&$scope.profile.user_profile_about_me!='null'&&$scope.profile.user_profile_about_me!=undefined){
			if($scope.profile.profile_photo!=''&&$scope.profile.profile_photo!=null&&$scope.profile.profile_photo!='null'&&$scope.profile.profile_photo!=undefined){
				$scope.joingroupStep =3;
			}else{
				$scope.joingroupStep =2;
			}
		}else{
			$scope.joingroupStep =1;				
		}
		$scope.aboutmeAjax = 0;
		$scope.aboutme = '';
		$scope.JoiningItem = '';
		$scope.JoiningItemTitle = '';
		$scope.JoiningItemType = '';
		$scope.JoiningItemseoTitile = '';
		$scope.joingingquestionnaire = [];
		$scope.md_questionnaire = [];
		$scope.md_option = [];
		$scope.md_checkbox0 = [];
		$scope.md_checkbox1 = [];
		$scope.md_checkbox2 = [];
		$scope.loadProfileUpload = function(){
			$('#join_group').modal('hide');
			$('.image-editor-group').cropit('imageSrc', '<?php echo $this->basePath();?>/public/images/profile-default-crop.jpg'); 
		}
		$scope.selectJoiningGroup= function(item_id,item_title,type,seoTitile){
			$scope.JoiningItem =item_id;
			$scope.JoiningItemTitle = item_title;
			$scope.JoiningItemType = type;
			$scope.JoiningItemseoTitile = seoTitile;
			if($scope.profile.user_profile_about_me!=''&&$scope.profile.user_profile_about_me!=null&&$scope.profile.user_profile_about_me!='null'&&$scope.profile.user_profile_about_me!=undefined){
				$scope.gotoGroupJoiningStep2();
			}else{ 	
				$scope.joingroupStep =1;
			}				
		}
		$scope.gotoGroupJoiningStep2 = function(){
			if(($scope.profile.profile_photo!=''&&$scope.profile.profile_photo!=null&&$scope.profile.profile_photo!='null'&&$scope.profile.profile_photo!=undefined)||($scope.profile.user_fbid!=''&&$scope.profile.user_fbid!=null&&$scope.profile.user_fbid!='null'&&$scope.profile.user_fbid!=undefined)){
				$scope.gotoGroupJoiningStep3();
			}else{
				$scope.joingroupStep =2;
			}
		}
		$scope.gotoGroupJoiningStep3 = function(){
			url = baseurl + '/groups/getQuestionnaire';
			$http.post(url,{group_id:$scope.JoiningItem},{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}
			).success(function(data, status, headers, config) {
				if(data.return_array.process_status == 'success'){
					if(data.return_array.questionnaire.length>0){
						$scope.joingingquestionnaire = data.return_array.questionnaire;
						$scope.joingroupStep =3;
					}else{
						$scope.gotoGroupJoiningStep4();
					}
				}else{
					$("#group_dialog").html(data.return_array.process_info);
					$("#group_dialog").dialog();						 
				}
			}).error(function(data, status, headers, config) {
				 //alert("Error occured. Please try again");
			});						 
		}
		$scope.gotoGroupJoiningStep4 = function(){
			url = baseurl + '/groups/joinGroup';
			$http.post(url,
			{										 
				group_id:$scope.JoiningItem,
			},{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}
			).success(function(data, status, headers, config) {
				if(data.return_array.process_status == 'success'){
					var array_index = $scope.getArrayIndex($scope.group_list,'group_id',$scope.JoiningItem);
					if($scope.group_list[array_index].group_type == 'public'){
						$scope.group_list[array_index].is_requested = 1;
					}else{
						$scope.group_list[array_index].is_member = 1;
					}
					$scope.joingroupStep =4;						
				}else{
					$("#group_dialog").html(data.return_array.process_info);
					$("#group_dialog").dialog();								
				}
			}).error(function(data, status, headers, config) {
				// alert("Error occured. Please try again");
			});	
		}
		$scope.aboutmeAjax =0;
		$scope.closeJoinWindow = function(){
			$("#join_group").modal("hide");
		}
		$scope.skipJoinRequest = function(step){
			if(step==1){
				$scope.gotoGroupJoiningStep2();
			}
			if(step==2){
				$scope.gotoGroupJoiningStep3();
			}
			if(step==3){
				$scope.gotoGroupJoiningStep4();
			}
		}
		$scope.SaveAboutMe = function(content){
			$scope.aboutme = content;
			if($scope.aboutme!=''&&$scope.aboutme!=null&&$scope.aboutme!='null'&&$scope.aboutme!=undefined){
				$scope.aboutmeAjax =1;
				url = baseurl + '/user/updateBio';
				$http.post(url,{bio:$scope.aboutme},{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}
				).success(function(data, status, headers, config) {
					if(data.return_array.process_status == 'success'){
						$scope.gotoGroupJoiningStep2(); 						 
						$scope.aboutmeAjax =0;							 
					}else{
						$("#group_dialog").html(data.return_array.process_info);
						$("#group_dialog").dialog();
						$scope.aboutmeAjax =0;		
					}
				}).error(function(data, status, headers, config) {
					// alert("Error occured. Please try again");
				});
			}else{
				$scope.gotoGroupJoiningStep2();
			}
		}
		$scope.cancelImageUpload = function(){
			$('#join_upload_profile-image').modal('hide');
			$('#join_group').modal('show');
			$scope.gotoGroupJoiningStep2();
			$scope.aboutmeAjax =0;
			$('.image-editor-group').cropit('imageSrc', '<?php echo $this->basePath();?>/public/images/profile-default-crop.jpg'); 
		}			
		$scope.cropImage = function(){			
			var imageData = $('.image-editor-group').cropit('export');
			if(imageData!=''){
				$scope.aboutmeAjax =1;	
				url = baseurl + '/user/updatProfilePic';
				$http.post(url,{imageData:imageData},{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}
				).success(function(data, status, headers, config) {
					if(data.return_array.process_status == 'success'){
						$('#join_upload_profile-image').modal('hide');								 
						$('#join_group').modal('show');	
						$scope.gotoGroupJoiningStep3();
						$scope.aboutmeAjax =0;												 
					}else{
						$("#group_dialog").html(data.return_array.process_info);
						$("#group_dialog").dialog();
						$scope.aboutmeAjax =0;		
					}
				}).error(function(data, status, headers, config) {
					//alert("Error occured. Please try again");
				}); 
			}else{
				$scope.gotoGroupJoiningStep3();
			}
		}
		$scope.checkInList = function(question_id,option_id,index){ 
			if(index==0){
				var index = $scope.md_checkbox0.indexOf(option_id);
				if(index!=-1) {return true;}
				else{return false;}
			}
			if(index==1){
				var index = $scope.md_checkbox1.indexOf(option_id);
				if(index!=-1) {return true;}
				else{return false;}
			}
			if(index==2){
				var index = $scope.md_checkbox2.indexOf(option_id);
				if(index!=-1) {return true;}
				else{return false;}
			}
			return false;				
		}
		$scope.selectedOptionRadio = function(question_id,option_id){ 
			$selectedOption = option_id;
			$scope.md_option[question_id] =  option_id
		}
		$scope.selectedOptionCheckbox = function(question_id,option_id,index){ 
			if(index==0){	
				var itemindex = $scope.md_checkbox0.indexOf(option_id);
				if(itemindex!=-1) {
					$scope.md_checkbox0.splice(itemindex,1); 
				}else{
					$scope.md_checkbox0.push(option_id); 
				}
			}
			if(index==1){						 	
				var itemindex = $scope.md_checkbox1.indexOf(option_id);
				if(itemindex!=-1) {
					$scope.md_checkbox1.splice(itemindex,1); 
				}else{
					$scope.md_checkbox1.push(option_id); 
				}
			}
			if(index==2){					 
				var itemindex = $scope.md_checkbox2.indexOf(option_id);
				if(itemindex!=-1) {
					$scope.md_checkbox2.splice(itemindex,1); 
				}else{
					$scope.md_checkbox2.push(option_id); 
				}
			}				  
		}
		$scope.saveQuestionnaireAnswers = function(){
			ince = 0;
			var questionanswers = [];
			angular.forEach($scope.joingingquestionnaire, function(dataset){					
				if(dataset.answer_type == 'Textarea'){
					questionanswers.push({'question_id':dataset.questionnaire_id,'answer':$scope.md_questionnaire[ince]});
				}
				if(dataset.answer_type == 'checkbox'){
					if(ince==0){
						 questionanswers.push({'question_id':dataset.questionnaire_id,'answer':$scope.md_checkbox0.join()});	
					 }
					  if(ince==1){
						 questionanswers.push({'question_id':dataset.questionnaire_id,'answer':$scope.md_checkbox1.join()});	
					 }
					  if(ince==2){
						 questionanswers.push({'question_id':dataset.questionnaire_id,'answer':$scope.md_checkbox2.join()});	
					 }	
				}
				if(dataset.answer_type == 'radio'){
					questionanswers.push({'question_id':dataset.questionnaire_id,'answer':$scope.md_option[dataset.questionnaire_id]});				  
				}
				ince++;
			});
			url = baseurl + '/groups/saveUserQuestionnaire';
			$http.post(url,
			{
				questionanswers:questionanswers,
				group_id:$scope.JoiningItem,
			},{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}
			).success(function(data, status, headers, config) {
				 if(data.return_array.process_status == 'success'){
					$scope.joingroupStep = 4;	
					$scope.aboutmeAjax =0;	
					var array_index = $scope.getArrayIndex($scope.group_list,'group_id',$scope.JoiningItem);
					if($scope.group_list[array_index].group_type == 'public'){
						$scope.group_list[array_index].is_requested = 1;
					}else{
						$scope.group_list[array_index].is_member = 1;
					}	
				 }else{
					$("#group_dialog").html(data.return_array.process_info);
					$("#group_dialog").dialog();
					 $scope.aboutmeAjax =0;		
				 }
			}).error(function(data, status, headers, config) {
				// alert("Error occured. Please try again");
			});					
		}
		$scope.reloadPage = function(){	
			window.location.reload();
		}
		$scope.showCountryDropdown = function(id,title){				 
			$scope.mygroup.country  = id,
			$scope.country_title = title,					 
			$scope.CitySelect($scope.mygroup.country);				
		}
		$scope.showCityDropdown = function(id,title){
			$scope.mygroup.city = id;
			$scope.city_selected = title;				
		}
		$scope.loadToolTip =function(id){
			$("#tooltip_"+id).show();
		}
		$scope.unloadToolTip =function(id){
			$("#tooltip_"+id).hide();
		}
		$scope.loadpeople = 0;
		$scope.friendsList = [];
		$scope.popup_group_id = '';
		$scope.popup_group_page = 1;
		$scope.groupFriends_count = 0;			
		$scope.LoadFriendsUsers = function(group_id,page,friends_count){
			$scope.loadpeople = 1;
			if(page==1){
				$scope.friendsList  = [];
			}
			$scope.popup_group_page = page;
			$scope.popup_group_id = group_id;
			$scope.groupFriends_count =friends_count;
			$('#friends_popup').modal();				
			url  = baseurl+'/groups/friendslist';
			$http.post(url,
			{	
				group_id:group_id,page:page,		 
			},
			{headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}	}	
			).success(function(data, status, headers, config) {
				if(data.return_array.process_status == 'success'){
					$scope.loadpeople = 0;
					if(page==1){
						$scope.friendsList  = data.return_array.friends;
					}else{
						$.merge($scope.friendsList, data.return_array.friends);	
					}						 
				}else{
					$("#group_dialog").html(data.return_array.process_info);
					$("#group_dialog").dialog();
				$("#"+system_type+"_"+content_id).html($compile(holder_content)($scope));					
				}				     
			}).error(function(data, status, headers, config) {
				// alert("Error occured. Please try again");
			});
		}
		$scope.enableScrollbarInvite= function(){
			$('#listed_members_container_inner').slimScroll({
				height: '140px'
			});
		}
		$scope.enabledscrollbarFriendsPopup = 0;
		$scope.enableScrollbarFriendsPopup= function(){					
			if($scope.enabledscrollbarFriendsPopup==0){ 
				$('#friends_list_outer').slimScroll({
					height: '250px'
				});
				$scope.enabledscrollbarFriendsPopup = 1;
			}				
		}
		$scope.addmoreOptions = function(optionindex){				 
			$scope.selectedOptionRange[optionindex] =  $scope.selectedOptionRange[optionindex]+1;
		}
			$scope.removeOptions = function(optionindex){
			$scope.selectedOptionRange[optionindex] =  $scope.selectedOptionRange[optionindex]-1;
		}	
		$scope.optionrange = function(n) {
			return new Array(n);
		}		
    });
	groupapp.directive('removeOnClick', function() {
		return {
			link: function(scope, elt, attrs) {
				scope.remove = function() {
					elt.remove();
				};
			}
		}
	});
	$( "#show_notification" ).click(function() {
		$( "#notifications-outer" ).toggle( "fast" );
	});
	$(".feed-refresh a").click(function() {
		$(".feed-refresh a").addClass("refresh-rotate");
	});
    $("#go_step-2").click(function() {
		$("#signup_step1").hide("fast");
		$("#signup_step2").show("fast");
	});
	$("#go_step-3").click(function() {
		$("#signup_step2").hide("fast");
		$("#signup_step3").show("fast");
	});
    function getFile(){  
        document.getElementById("btnUploadImage").click();
    }
    function fncResetForm(){
        $('#txtGroupName').val('');
        $('#CountryDropDown').find('.customSelectInner').html('');
        $('#CityDropDown').find('.customSelectInner').html('');
        $('#categoryDropDown').find('.customSelectInner').html('');
        $("input:radio[name=group_type][disabled=false]:first").attr('checked', true);
        $('#hdnoldimage').val('');
        $('#hdnTagId').val('');
        $('#txtDescription').val('');
        $('#imgUserImage').attr('src','');
		uploadFIle = '';
		$('#uploadPreview').html('');
    }
	$(document).on("click","#group_creat_butn",function(){
		var dropbox = document.getElementById("uplodbtn");
		// init event handlers
		dropbox.addEventListener("dragenter", dragEnter, false);
		dropbox.addEventListener("dragexit", dragExit, false);
		dropbox.addEventListener("dragover", dragOver, false);
		dropbox.addEventListener("drop", drop, false);	 
	});
	function dragEnter(evt) {
		evt.stopPropagation();
		evt.preventDefault();
	}
	function dragExit(evt) {
		evt.stopPropagation();
		evt.preventDefault();
	}
	function dragOver(evt) {
		evt.stopPropagation();
		evt.preventDefault();
	}
	function drop(evt) {  
		evt.stopPropagation();
		evt.preventDefault();
		var files = evt.dataTransfer.files;		
		//if (navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1) {alert(1);alert(evt.target.files[0].name);$("#imgUserImage").html(files.name);}		
		var count = files.length;
		// Only call the handler if 1 or more files was dropped.
		if (count > 0)
			handleFiles(files);
	}
	function handleFiles(files) {
		var file = files[0];		 
		uploadFIle = files[0];
		moveFiletoTemp(); 
		//var reader = new FileReader();	 
		//reader.onloadend = handleReaderLoadEnd; 
		//reader.readAsDataURL(file);
	}
	function handleReaderProgress(evt) {
		if (evt.lengthComputable) {
			var loaded = (evt.loaded / evt.total);
			$("#progressbar").progressbar({ value: loaded * 100 });
		}
	}
	function handleReaderLoadEnd(evt) {
		var img = document.getElementById("imgUserImage");
		img.src = evt.target.result;
		$("#default_img").hide();
		$("#uploaded_img").show();	 
	}
	angular.element(document).ready(function() {
		angular.bootstrap(document.getElementById("profile_div"), ["myapp"]);
		angular.bootstrap(document.getElementById("group_right_container"), ["groupapp"]);
	});
	$(document).on('change','#btnUploadImage',function(e){ 
		fileInput = e.target.files;
		uploadFIle = fileInput[0];
		moveFiletoTemp(); 	 
	});
	function moveFiletoTemp(){
		var formData = new FormData();	
		var url = baseurl+'/user/uploadhandler';
		formData.append("mediaImage",uploadFIle);
		$("#ImageUploadStatus").html('<img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif" />');	
		//document.getElementById("imgUserImage").src='<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif';
		$("#progress").html('<div class="progress_status"></div>');
		$.ajax({
			type: 'POST',
			url: url,
			data: formData,
			cache: false,		 
			contentType: false,
			processData: false,	 
			success: function(response) {
				$("#ImageUploadStatus").html('');
				$("#progress").html('');
				if(response.return_array.process_status == 'success'){				
					$("#default_img").hide();
					$("#uploaded_img").show();				
					document.getElementById("imgUserImage").src=response.return_array.image_url;
					$("#image_error").html('');
					$("#image_error").fadeOut("slow");
				}else{	
					$("#image_error").html(response.return_array.process_info);
					$("#image_error").fadeIn("slow");
					$("#default_img").show();
					$("#uploaded_img").hide();						 
				}	
			},
			error: function(xhr, ajaxOptions, thrownError) {		 			
				$("#image_error").html("<?php echo $this->translate("upload failed.Please try again",'default'); ?>");
				$("#image_error").fadeIn("slow");			 
			}		
		});
	}
	$(function() {			
        $('.image-editor-group').cropit({
			exportZoom: 1.25,
			imageBackground: true,
			imageBackgroundBorderWidth: 20,
			imageState: {
				src: '<?php echo $this->basePath();?>/public/images/profile-default-crop.jpg'
			}
        });
        $('.export').click(function() {
			var imageData = $('.image-editor-group').cropit('export');
			window.open(imageData);
        });
    });
	var tabindexes = 0;
	$(document).on('keypress','#invite_list_friend',function(e){
		var selected_items = $("#hid_filterFriends").val();
		if(tabindexes>=selected_items){tabindexes=tabindexes-1;}
		$('#invite_list_friend_ul li').removeClass("selected_member");
		if(e.keyCode == 38){
			if(tabindexes>0&&tabindexes<selected_items){tabindexes--}
			$('#myfriend'+tabindexes).addClass("selected_member");
		}
		if(e.keyCode == 40){
			if(tabindexes>=0&&tabindexes<selected_items){tabindexes++}
			$('#myfriend'+tabindexes).addClass("selected_member");
		}
		if(e.keyCode == 13){
			$('#myfriend'+tabindexes).trigger( "click" );
		}
	});
	$(document).on('click','#invite_list_friend',function(e){
		$("#listed_members_container").show();
	});
	var profilepic = [];
	$(document).on('change','#profile_image_file',function(e){			  
		fileInput = e.target.files;
		profilepic = fileInput[0];
		moveProfilepictoTemp(); 	 
	});	
	function moveProfilepictoTemp(){
		var formData = new FormData();	
		var url = baseurl+'/user/uploadhandler';
		formData.append("mediaImage",profilepic);
		//$("#ImageUploadStatus").html('<img src="<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif" />');	
		//document.getElementById("imgUserImage").src='<?php echo $this->basePath(); ?>/public/images/ajax_loader.gif';
		$("#profilepic_process").html('<div class="progress_status"></div>');
		$.ajax({
			type: 'POST',
			url: url,
			data: formData,
			cache: false,		 
			contentType: false,
			processData: false,	 
			success: function(response) {
				//$("#ImageUploadStatus").html('');
				$("#profilepic_process").html('');
				if(response.return_array.process_status == 'success'){ 
					$('.image-editor-group').cropit('imageSrc', response.return_array.image_url); 
				}else{	
					$("#group_dialog").html(response.return_array.process_info);
					$( "#group_dialog" ).dialog();				 
				}	
			},
			error: function(xhr, ajaxOptions, thrownError) {		 			
				$("#group_dialog").html("<?php echo $this->translate("upload failed.Please try again",'default'); ?>");
				$( "#group_dialog" ).dialog(); 
			}		
		});
	}
	$(document).on("click","#loadProfileUpload",function(){
		var dropbox = document.getElementById("profile_pic_editor");
		// init event handlers
		dropbox.addEventListener("dragenter", dragEnterProfile, false);
		dropbox.addEventListener("dragexit", dragExitProfile, false);
		dropbox.addEventListener("dragover", dragOverProfile, false);
		dropbox.addEventListener("drop", dropProfile, false);	 
	});
	function dragEnterProfile(evt) {
		evt.stopPropagation();
		evt.preventDefault();
	}
	function dragExitProfile(evt) {
		evt.stopPropagation();
		evt.preventDefault();
	}
	function dragOverProfile(evt) {
		evt.stopPropagation();
		evt.preventDefault();
	}
	function dropProfile(evt) {  
		evt.stopPropagation();
		evt.preventDefault();
		var files = evt.dataTransfer.files;		
		//if (navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1) {alert(1);alert(evt.target.files[0].name);$("#imgUserImage").html(files.name);}		
		var count = files.length;
		// Only call the handler if 1 or more files was dropped.
		if (count > 0)
			handleFilesProfile(files);
	}
	function handleFilesProfile(files) {
		var file = files[0];	 
		profilepic = files[0];
		moveProfilepictoTemp(); 
		//var reader = new FileReader();	 
		//reader.onloadend = handleReaderLoadEnd; 
		//reader.readAsDataURL(file);
	}
	function handleReaderProgress(evt) {
		if (evt.lengthComputable) {
			var loaded = (evt.loaded / evt.total);
			$("#progressbar").progressbar({ value: loaded * 100 });
		}
	}
	function handleReaderLoadEnd(evt) {
		var img = document.getElementById("imgUserImage");
		img.src = evt.target.result;
		$("#default_img").hide();
		$("#uploaded_img").show();	 
	}
	var invite_listenabled = 0;
	$(document).on('click','#create_group',function(e){
		if(invite_listenabled==0){
			$("#listed_members_container").hide();
		}
	});
	$(document).on('mouseenter','#invite_list_friend',function(e){
		invite_listenabled = 1;
	});
	$(document).on('mouseleave','#invite_list_friend',function(e){
		invite_listenabled = 0;
	});
	$(document).on('mouseenter','#listed_members_container',function(e){
		invite_listenabled = 1;
	});
	$(document).on('mouseleave','#listed_members_container',function(e){
		invite_listenabled = 0;
	});
	$(document).on("click","#removeUploaded",function(){
		$("#uploaded_img").hide();
		$("#default_img").show();
		uploadFIle = [];
	});
</script>
