<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Jeera Admin - Dashboard</title>

    <!-- Bootstrap Core CSS -->
      <?php echo $this->headTitle('Jeera Admin')->setSeparator(' - ')->setAutoEscape(false); ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>
    <?php echo 
    $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/favicon.icon', 'href' => $this->basePath() . '/public/images/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/public/css/responsive-calendar.css')
        ->prependStylesheet($this->basePath() . '/public/font-awesome-4.1.0/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/public/css/plugins/morris.css')
        ->prependStylesheet($this->basePath() . '/public/css/jeera-admin.css') 
        ->prependStylesheet($this->basePath() . '/public/css/plugins/timeline.css')
        ->prependStylesheet($this->basePath() . '/public/css/plugins/metisMenu/metisMenu.min.css')
        ->prependStylesheet($this->basePath() . '/public/css/bootstrap.min.css'); ?>

    <?php $this->HeadScript()->prependFile($this->basePath().'/public/js/jquery-1.11.0.js','text/javascript'); ?>
    <?php $this->HeadScript()->appendFile($this->basePath().'/public/js/bootstrap.min.js','text/javascript'); ?>
    <?php $this->HeadScript()->appendFile($this->basePath().'/public/js/plugins/metisMenu/metisMenu.min.js','text/javascript'); ?>
    <?php $this->HeadScript()->appendFile($this->basePath().'/public/js/jeera-admin.js','text/javascript'); ?>
    <?php $this->HeadScript()->appendFile($this->basePath().'/public/js/responsive-calendar.js','text/javascript'); ?>
    <?php echo $this->headScript(); ?>
 
   <script type="text/javascript">
      var base_url = '<?php echo $this->basePath(); ?>';
      $(document).ready(function () {        
        var d = new Date();
        var month = d.getMonth()+1;
        var day = d.getDate();
        var year = d.getFullYear();
        var arrResponse = new Array();
        var noOfDays  = daysInMonth(month,year);
        var dateformated = '';       
        // fetch all the events on the basis of date
        $.ajax({
            type: 'POST',
            beforeSend: function ()
            {
            },
            complete: function ()
            {
            },
            url: base_url + '/jadmin/geteventmonthwise',
            data: {
                strDate   : year+'-'+month
            },
            dataType: 'json',
            success: function (response)
            {
                // If response is success
                if(response.return_array.process_status == 'success'){
                    
                    //Get all the events 
                    var arrResponse  = response.return_array.event;                   
                   
                    var data = '{';
                    for(var i=0; i< arrResponse.length; i++){                  
                        dateformated = '"number":'+arrResponse[i]['event']+',"url":"'+base_url+'/jadmin/eventlist/'+arrResponse[i]['date']+'/'+arrResponse[i]['event']+'"';
                        if(i == arrResponse.length-1){
                         data += '"'+arrResponse[i]['date']+'":{'+dateformated+'}';    
                        }else{
                         data += '"'+arrResponse[i]['date']+'":{'+dateformated+'},'    
                        }  
                    }
                    data += '}';                   
            
            $(".responsive-calendar").responsiveCalendar({
                    time: year+'-'+month,
                    events: JSON.parse(data)
                  });   
                }
            },
            error: function (e)
            {   //Show calendar in case of failure response
                $(".responsive-calendar").responsiveCalendar({
                    time: year+'-'+month,                  
                    events: JSON.parse(data)
                });
            }               
        })     
    });
    
    function daysInMonth(month,year) {
         return new Date(year, month, 0).getDate();
     }
    </script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    </head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand header_logo" href="index.html"><img src="<?php echo $this->basePath();?>/public/images/jeera-logo-2.png" alt="" /></a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                       <li><a href="<?php echo $this->url('jadmin/admindetail'); ?>"><i class="fa fa-user fa-fw"></i>Settings</a></li>
                        <li><a href="<?php echo $this->url('jadmin/resetpassword'); ?>"><i class="fa fa-user fa-fw"></i>Password Reset</a></li>
                       
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->url('jadmin/logout') ?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav admin_left-menu" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button"><i class="fa fa-search"></i></button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a class="active" href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-tags fa-fw"></i> Interests<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="<?php echo $this->url('jadmin/admin-tags-category') ?>">Interest Category </a></li>
                                <li><a href="<?php echo $this->url('jadmin/admin-tags') ?>">Manage Interest</a></li>
                                <li><a href="<?php echo $this->url('jadmin/admin-user-tags') ?>">Manage User Interests</a></li>
                                <li><a href="<?php echo $this->url('jadmin/admin-planet-tags') ?>">Manage Group Interests</a></li>
                                
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-tags fa-fw"></i> Admin Access Control<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="<?php echo $this->url('jadmin/admin-acl-roles') ?>">Acl Roles </a></li>
                                <li><a href="<?php echo $this->url('jadmin/admin-acl-resource') ?>">Acl Resource</a></li>
                                <!-- <li><a href="<?php //echo $this->url('jadmin/admin-acl-resource-to-roles') ?>">Acl Resource to roles</a></li> -->
                                <li><a href="<?php echo $this->url('jadmin/admin-backend-user') ?>">Admin Users</a></li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li><a href="<?php echo $this->url('jadmin/admin-planet') ?>"><i class="fa fa-group fa-fw"></i> Manage Groups</a></li>
                        <li><a href="<?php echo $this->url('jadmin/admin-activity') ?>"><i class="fa fa-calendar fa-fw"></i> Activities</a></li>
                        <li><a href="<?php echo $this->url('jadmin/admin-users') ?>"><i class="fa fa-user fa-fw"></i> Users</a></li>
                        <li><a href="#"><i class="fa fa-navicon fa-fw"></i> Spams<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="<?php echo $this->url('jadmin/admin-spamreasons') ?>"><i class="fa fa-warning fa-fw"></i> Spam Resons</a></li>
                                <li><a href="<?php echo $this->url('jadmin/admin-spamreports') ?>">Spam Reports</a></li>
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->url('jadmin/admin-notification') ?>"><i class="fa fa-bell fa-fw"></i> Notification</a></li>
                        <li>
                            <a href="#"><i class="fa fa-navicon fa-fw"></i> Others<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="<?php echo $this->url('jadmin/admin-country') ?>">Country List</a></li>
                                <li><a href="<?php echo $this->url('jadmin/admin-city') ?>">
                                City List</a></li>
                                <li><a href="<?php echo $this->url('jadmin/admin-tags-popular') ?>">Popular Tags</a></li>
                                <li><a href="<?php echo $this->url('jadmin/admin-groups-popular') ?>">Popular Groups</a></li>
                                <li><a href="<?php echo $this->url('jadmin/admin-users-popular') ?>">Popular Users</a></li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            
            <?php echo $this->content; ?>
            
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

</body>

</html>