<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Jeera Admin Login</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond./public/js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?php echo $this->headTitle('Jeera Admin')->setSeparator(' - ')->setAutoEscape(false); ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>
        <?php echo 
        $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/favicon.icon', 'href' => $this->basePath() . '/public/images/favicon.ico'))

                        ->prependStylesheet($this->basePath() . '/public/font-awesome-4.1.0/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/public/css/plugins/metisMenu/metisMenu.min.css')
                        ->prependStylesheet($this->basePath() . '/public/css/jeera-admin.css') 
                        ->prependStylesheet($this->basePath() . '/public/css/bootstrap.min.css'); ?>

        <?php $this->HeadScript()->prependFile($this->basePath().'/public/js/jquery-1.11.0.js','text/javascript'); ?>
        <?php $this->HeadScript()->appendFile($this->basePath().'/public/js/bootstrap.js','text/javascript'); ?>
        <?php $this->HeadScript()->appendFile($this->basePath().'/public/js/plugins/metisMenu/metisMenu.min.js','text/javascript'); ?>
        <?php $this->HeadScript()->appendFile($this->basePath().'/public/js/jeera-admin.js','text/javascript'); ?>
        <?php echo $this->headScript(); ?>

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel">
                    <div class="logo-login"><img src="<?php echo $this->basePath();?>/public/images/jeera-logo-2.png" alt="" /></div>
                    
                <div class="panel panel-default login-outer">
                    <div class="panel-body">
                        <?php echo $this->content; ?>
                    </div>
                </div>
                
                </div>
            </div>
        </div>
    </div>

</body>

</html>

