<?php 

if (defined('RUNNING_FROM_ROOT')) {

  //$this->plugin('basePath')->setBasePath($this->basePath().'/public');

}

?>

<?php echo $this->doctype(); ?> 

<html xmlns="http://www.w3.org/1999/xhtml">

    <head>

        <meta charset="utf-8">

		<?php echo $this->headTitle('Jeera')->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1'); ?>

		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/favicon.icon', 'href' => $this->basePath() . '/public/images/favicon.ico'))
						->prependStylesheet($this->basePath() . '/public/css/responsive.css')	
                        ->prependStylesheet($this->basePath() . '/public/css/styles.css')	
							->appendStylesheet($this->basePath() . '/public/css/jquery-ui.css')
						->prependStylesheet($this->basePath() . '/public/css/bootstrap.css')	

						; ?>
		<?php $this->HeadScript()->prependFile($this->basePath().'/public/js/jquery-ui.js','text/javascript'); ?>
		<?php $this->HeadScript()->prependFile($this->basePath().'/public/js/jquery-1.11.1.min.js','text/javascript'); ?>

		<?php $this->HeadScript()->appendFile($this->basePath().'/public/js/bootstrap.js','text/javascript'); ?> 

		<?php $this->HeadScript()->appendFile($this->basePath().'/public/js/modernizr.js','text/javascript'); ?>

		<?php $this->HeadScript()->appendFile($this->basePath().'/public/js/jquery-customSelect.js','text/javascript'); ?>		 

		<?php echo $this->headScript(); ?>	

		<script>var baseurl = '<?php echo $this->basePath(); ?>'</script>
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js"></script>
		<?php if($locales_selected=='ar_AE'){
			?>
			<link href="<?php echo $this->basePath(); ?>/public/css/bootstrap-rtl.min.css" media="screen" rel="stylesheet" type="text/css">
			<link href="<?php echo $this->basePath(); ?>/public/css/style_ar.css" media="screen" rel="stylesheet" type="text/css">
			<?php
		} ?>
	</head>

    <body class="signup-bg">    

    <?php echo $this->content; ?>

    </body>

</html>



