<div style="background-color:#cccccc; width:500px; margin:0 auto; padding:20px 0;">
<table width="469" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
	<td><img src="<?php echo BASE_URL; ?>/public/images/mail/banner.png" alt="" style="float:left; width:100%;" /></td>
  </tr>
  <tr>
	<td style="background-color:#fff;">
	  <div style="padding:25px; font-family:'Trebuchet MS', Arial, Verdana; font-size:13px; line-height:25px; color:#8f8f8f; text-align:center;">
			<p style="font-size:17px; color:#393939;">Forgot Password</p>
			<p>We got a password reset request from you. Please click the button given below for resetting your password.</p>
			<p><a href="<?php echo BASE_URL; ?>/user/resetpassword/<?php echo $user_verification_key.'/'.$user_recoverId; ?>" style="background-color:#f1c411; color:#fff; font-size:17px; padding:8px 25px; display:inline-block; text-decoration:none; -moz-border-radius:20px; -webkit-border-radius:20px; -o-border-radius:20px; -ms-border-radius:20px; border-radius:20px; margin:25px 0;">Click Here</a></p>
			<p style="margin-bottom:30px;">This link will expire within 3 days. </p>
			
			<div style="padding-top:25px;">
				<p>
					<a href="jabascript:void(0);"><img src="<?php echo BASE_URL; ?>/public/images/mail/tw-icon.png" alt="" /></a> <a href="jabascript:void(0);"><img src="<?php echo BASE_URL; ?>/public/images/mail/fb-icon.png" alt="" /></a><br />
					&copy;2015 Jeera. All rights reserved.
				</p>
			</div>
	  </div>
	</td>
  </tr>
</table>
</div>
