
    <div class="jeera-fixed-header" style="text-align:center;">
		<div class="header-fixed-inner">
			<div style="padding-top:15px;"><a href="<?php echo $this->basePath(); ?>"><img src="<?php echo $this->basePath(); ?>/public/images/jeera-logo-2.png" alt="" /></a></div>
		</div>
	</div>
    
    
    <div class="feed-filter_outer sub_top-margin">
    	<div class="home-container"><h1 style="text-align:center;"><strong>Terms Of Use</strong></h1></div>
    </div>
    
    <div class="home-container feeds-container">
    	<div class="group-view-outer">
        	<div class="row">
            	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                	<div class="post-outer terms-outer border_radius">
                        
                        <div class="post_status-text view_status">
                            <h2>Explore</h2>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                            <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
                            <h2>Feeds</h2>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                            
                            
                        </div>
                        
                        
                    </div>
                </div>
                
                <div class="clear"></div>
            </div>
        </div>
        
    </div>